CREATE TABLE `activity_hot_blood_war` (
 `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `playerId` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `termId` int(11) NOT NULL DEFAULT '0',
 `cureArmyInfos` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `cureFirstType` int(11) NOT NULL DEFAULT '0',
 `cureArmyId` int(11) NOT NULL DEFAULT '0',
 `cureArmyStartTime` bigint(20) NOT NULL DEFAULT '0',
 `cureArmySpeedTime` bigint(20) NOT NULL DEFAULT '0',
 `cureArmyCalTime` bigint(20) NOT NULL DEFAULT '0',
 `loginDays` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `achieveItems` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `selfHurtInfo` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `enemyKillInfo` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `enemyKillScore` bigint(20) NOT NULL DEFAULT '0',
 `selfHurtScore` bigint(20) NOT NULL DEFAULT '0',
 `finishCheck` int(11) NOT NULL DEFAULT '0',
 `initTime` bigint(20) NOT NULL DEFAULT '0',
 `updateTime` bigint(20) NOT NULL DEFAULT '0',
 `createTime` bigint(20) NOT NULL DEFAULT '0',
 `invalid` tinyint(1) NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`),
 KEY `playerId_index` (`playerId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
