CREATE TABLE `activity_new_start` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `playerId` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `termId` int(11) NOT NULL DEFAULT '0',
  `createTime` bigint(20) NOT NULL DEFAULT '0',
  `updateTime` bigint(20) NOT NULL DEFAULT '0',
  `invalid` tinyint(1) NOT NULL DEFAULT '0',
  `startTime` bigint(20) NOT NULL DEFAULT '0',
  `overTime` bigint(20) NOT NULL DEFAULT '0',
  `isActive` tinyint(1) NOT NULL DEFAULT '0',
  `isBind` tinyint(1) NOT NULL DEFAULT '0',
  `playerLevel` int(11) NOT NULL DEFAULT '0',
  `vipLevel` int(11) NOT NULL DEFAULT '0',
  `baseLevel` int(11) NOT NULL DEFAULT '0',
  `heroCount` int(11) NOT NULL DEFAULT '0',
  `equipTechLevel` int(11) NOT NULL DEFAULT '0',
  `jijiaLevel` int(11) NOT NULL DEFAULT '0',
  `name` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `icon` int(11) NOT NULL DEFAULT '0',
  `pfIcon` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `oldPlayerId` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `oldServerId` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `cfgInfo` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `awardInfo` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `playerId_index` (`playerId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;