CREATE TABLE `activity_submarine_war` (
 `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `playerId` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `termId` int(11) NOT NULL DEFAULT '0',
 `gameInfo` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `gameScore` int(11) NOT NULL DEFAULT '0',
 `gameCount` int(11) NOT NULL DEFAULT '0',
 `buyGameCount` int(11) NOT NULL DEFAULT '0',
 `gameLevelMax` int(11) NOT NULL DEFAULT '0',
 `gameScoreMax` int(11) NOT NULL DEFAULT '0',
 `gameScoreMaxTime` int(11) NOT NULL DEFAULT '0',
 `skillItemBuyInfo` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `buyInfo` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `achieveItems` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `loginDays` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `tips` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `initTime` bigint(20) NOT NULL DEFAULT '0',
 `createTime` bigint(20) NOT NULL DEFAULT '0',
 `updateTime` bigint(20) NOT NULL DEFAULT '0',
 `invalid` tinyint(1) NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`),
 KEY `playerId_index` (`playerId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;