CREATE TABLE `activity_plant_weapon` (
 `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `playerId` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `termId` int(11) NOT NULL DEFAULT '0',
 `turnCount` int(11) NOT NULL DEFAULT '0',
 `dayTime` bigint(20) NOT NULL DEFAULT '0',
 `continueDraws` int(11) NOT NULL DEFAULT '0',
 `continueGiveups` int(11) NOT NULL DEFAULT '0',
 `cooldownTime` bigint(20) NOT NULL DEFAULT '0',
 `inspireProgress` int(11) NOT NULL DEFAULT '0',
 `consumeItemCount` int(11) NOT NULL DEFAULT '0',
 `awardItems` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `shopItems` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `disCount` int(11) NOT NULL DEFAULT '0',
 `achieveItems` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `createTime` bigint(20) NOT NULL DEFAULT '0',
 `updateTime` bigint(20) NOT NULL DEFAULT '0',
 `invalid` tinyint(1) NOT NULL DEFAULT '0',
 `choosePlantWeapon` int(11) NOT NULL DEFAULT '0',
 `dailyRecieveTime` bigint(20) NOT NULL DEFAULT '0',
 `touchCount` int(11) NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`),
 KEY `playerId_index` (`playerId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;