// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Analyze.proto

package com.hawk.game.protocol;

public final class Analyze {
  private Analyze() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ActionType}
   *
   * <pre>
   * 操作类型
   * </pre>
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHAT = 1;</code>
     *
     * <pre>
     * 聊天
     * </pre>
     */
    CHAT(0, 1),
    /**
     * <code>PAGE_OPEN = 2;</code>
     *
     * <pre>
     * 打开页面
     * </pre>
     */
    PAGE_OPEN(1, 2),
    /**
     * <code>WORLD_FRAME = 3;</code>
     *
     * <pre>
     * 世界的帧率
     * </pre>
     */
    WORLD_FRAME(2, 3),
    /**
     * <code>TOWN_FRAME = 4;</code>
     *
     * <pre>
     * 城内的帧率
     * </pre>
     */
    TOWN_FRAME(3, 4),
    /**
     * <code>BATTLE_FRAME = 5;</code>
     *
     * <pre>
     * 战斗时的帧率
     * </pre>
     */
    BATTLE_FRAME(4, 5),
    /**
     * <code>REQUEST = 6;</code>
     *
     * <pre>
     * 网络请求
     * </pre>
     */
    REQUEST(5, 6),
    /**
     * <code>LOADSCENE_TIME = 7;</code>
     *
     * <pre>
     * 登录场景耗时
     * </pre>
     */
    LOADSCENE_TIME(6, 7),
    /**
     * <code>LOADSCENE_FRAME = 8;</code>
     *
     * <pre>
     * 登录场景帧数
     * </pre>
     */
    LOADSCENE_FRAME(7, 8),
    /**
     * <code>UPDATEVER_TIME = 9;</code>
     *
     * <pre>
     * 版本场景耗时
     * </pre>
     */
    UPDATEVER_TIME(8, 9),
    /**
     * <code>UPDATEVER_FRAME = 10;</code>
     *
     * <pre>
     * 版本场景帧数
     * </pre>
     */
    UPDATEVER_FRAME(9, 10),
    /**
     * <code>LOGINSDK_TIME = 11;</code>
     *
     * <pre>
     * 登录SDK场景耗时
     * </pre>
     */
    LOGINSDK_TIME(10, 11),
    /**
     * <code>LOGINSDK_FRAME = 12;</code>
     *
     * <pre>
     * 登录SDK场景帧数
     * </pre>
     */
    LOGINSDK_FRAME(11, 12),
    /**
     * <code>SERVERLIST_TIME = 13;</code>
     *
     * <pre>
     * 服务器列表场景耗时
     * </pre>
     */
    SERVERLIST_TIME(12, 13),
    /**
     * <code>SERVERLIST_FRAME = 14;</code>
     *
     * <pre>
     * 服务器列表场景帧数
     * </pre>
     */
    SERVERLIST_FRAME(13, 14),
    /**
     * <code>GRAYUPDATE_TIME = 15;</code>
     *
     * <pre>
     * 灰度更新场景耗时
     * </pre>
     */
    GRAYUPDATE_TIME(14, 15),
    /**
     * <code>GRAYUPDATE_FRAME = 16;</code>
     *
     * <pre>
     * 灰度更新场景帧数
     * </pre>
     */
    GRAYUPDATE_FRAME(15, 16),
    /**
     * <code>PRELOAD_TIME = 17;</code>
     *
     * <pre>
     * 预加载场景耗时
     * </pre>
     */
    PRELOAD_TIME(16, 17),
    /**
     * <code>PRELOAD_FRAME = 18;</code>
     *
     * <pre>
     * 预加载场景帧数
     * </pre>
     */
    PRELOAD_FRAME(17, 18),
    /**
     * <code>LOGINSERVER_TIME = 19;</code>
     *
     * <pre>
     * 登录服务器场景耗时
     * </pre>
     */
    LOGINSERVER_TIME(18, 19),
    /**
     * <code>LOGINSERVER_FRAME = 20;</code>
     *
     * <pre>
     * 登录服务器场景帧数
     * </pre>
     */
    LOGINSERVER_FRAME(19, 20),
    /**
     * <code>GAMENEWBIE_TIME = 21;</code>
     *
     * <pre>
     * 新手场景耗时
     * </pre>
     */
    GAMENEWBIE_TIME(20, 21),
    /**
     * <code>GAMENEWBIE_FRAME = 22;</code>
     *
     * <pre>
     * 新手场景帧数
     * </pre>
     */
    GAMENEWBIE_FRAME(21, 22),
    /**
     * <code>GAMEINTROSTATE_TIME = 23;</code>
     *
     * <pre>
     * 新手耗时
     * </pre>
     */
    GAMEINTROSTATE_TIME(22, 23),
    /**
     * <code>GAMEINTROSTATE_FRAME = 24;</code>
     *
     * <pre>
     * 新手帧数
     * </pre>
     */
    GAMEINTROSTATE_FRAME(23, 24),
    /**
     * <code>PUSH = 25;</code>
     *
     * <pre>
     * 客户端推送数据
     * </pre>
     */
    PUSH(24, 25),
    ;

    /**
     * <code>CHAT = 1;</code>
     *
     * <pre>
     * 聊天
     * </pre>
     */
    public static final int CHAT_VALUE = 1;
    /**
     * <code>PAGE_OPEN = 2;</code>
     *
     * <pre>
     * 打开页面
     * </pre>
     */
    public static final int PAGE_OPEN_VALUE = 2;
    /**
     * <code>WORLD_FRAME = 3;</code>
     *
     * <pre>
     * 世界的帧率
     * </pre>
     */
    public static final int WORLD_FRAME_VALUE = 3;
    /**
     * <code>TOWN_FRAME = 4;</code>
     *
     * <pre>
     * 城内的帧率
     * </pre>
     */
    public static final int TOWN_FRAME_VALUE = 4;
    /**
     * <code>BATTLE_FRAME = 5;</code>
     *
     * <pre>
     * 战斗时的帧率
     * </pre>
     */
    public static final int BATTLE_FRAME_VALUE = 5;
    /**
     * <code>REQUEST = 6;</code>
     *
     * <pre>
     * 网络请求
     * </pre>
     */
    public static final int REQUEST_VALUE = 6;
    /**
     * <code>LOADSCENE_TIME = 7;</code>
     *
     * <pre>
     * 登录场景耗时
     * </pre>
     */
    public static final int LOADSCENE_TIME_VALUE = 7;
    /**
     * <code>LOADSCENE_FRAME = 8;</code>
     *
     * <pre>
     * 登录场景帧数
     * </pre>
     */
    public static final int LOADSCENE_FRAME_VALUE = 8;
    /**
     * <code>UPDATEVER_TIME = 9;</code>
     *
     * <pre>
     * 版本场景耗时
     * </pre>
     */
    public static final int UPDATEVER_TIME_VALUE = 9;
    /**
     * <code>UPDATEVER_FRAME = 10;</code>
     *
     * <pre>
     * 版本场景帧数
     * </pre>
     */
    public static final int UPDATEVER_FRAME_VALUE = 10;
    /**
     * <code>LOGINSDK_TIME = 11;</code>
     *
     * <pre>
     * 登录SDK场景耗时
     * </pre>
     */
    public static final int LOGINSDK_TIME_VALUE = 11;
    /**
     * <code>LOGINSDK_FRAME = 12;</code>
     *
     * <pre>
     * 登录SDK场景帧数
     * </pre>
     */
    public static final int LOGINSDK_FRAME_VALUE = 12;
    /**
     * <code>SERVERLIST_TIME = 13;</code>
     *
     * <pre>
     * 服务器列表场景耗时
     * </pre>
     */
    public static final int SERVERLIST_TIME_VALUE = 13;
    /**
     * <code>SERVERLIST_FRAME = 14;</code>
     *
     * <pre>
     * 服务器列表场景帧数
     * </pre>
     */
    public static final int SERVERLIST_FRAME_VALUE = 14;
    /**
     * <code>GRAYUPDATE_TIME = 15;</code>
     *
     * <pre>
     * 灰度更新场景耗时
     * </pre>
     */
    public static final int GRAYUPDATE_TIME_VALUE = 15;
    /**
     * <code>GRAYUPDATE_FRAME = 16;</code>
     *
     * <pre>
     * 灰度更新场景帧数
     * </pre>
     */
    public static final int GRAYUPDATE_FRAME_VALUE = 16;
    /**
     * <code>PRELOAD_TIME = 17;</code>
     *
     * <pre>
     * 预加载场景耗时
     * </pre>
     */
    public static final int PRELOAD_TIME_VALUE = 17;
    /**
     * <code>PRELOAD_FRAME = 18;</code>
     *
     * <pre>
     * 预加载场景帧数
     * </pre>
     */
    public static final int PRELOAD_FRAME_VALUE = 18;
    /**
     * <code>LOGINSERVER_TIME = 19;</code>
     *
     * <pre>
     * 登录服务器场景耗时
     * </pre>
     */
    public static final int LOGINSERVER_TIME_VALUE = 19;
    /**
     * <code>LOGINSERVER_FRAME = 20;</code>
     *
     * <pre>
     * 登录服务器场景帧数
     * </pre>
     */
    public static final int LOGINSERVER_FRAME_VALUE = 20;
    /**
     * <code>GAMENEWBIE_TIME = 21;</code>
     *
     * <pre>
     * 新手场景耗时
     * </pre>
     */
    public static final int GAMENEWBIE_TIME_VALUE = 21;
    /**
     * <code>GAMENEWBIE_FRAME = 22;</code>
     *
     * <pre>
     * 新手场景帧数
     * </pre>
     */
    public static final int GAMENEWBIE_FRAME_VALUE = 22;
    /**
     * <code>GAMEINTROSTATE_TIME = 23;</code>
     *
     * <pre>
     * 新手耗时
     * </pre>
     */
    public static final int GAMEINTROSTATE_TIME_VALUE = 23;
    /**
     * <code>GAMEINTROSTATE_FRAME = 24;</code>
     *
     * <pre>
     * 新手帧数
     * </pre>
     */
    public static final int GAMEINTROSTATE_FRAME_VALUE = 24;
    /**
     * <code>PUSH = 25;</code>
     *
     * <pre>
     * 客户端推送数据
     * </pre>
     */
    public static final int PUSH_VALUE = 25;


    public final int getNumber() { return value; }

    public static ActionType valueOf(int value) {
      switch (value) {
        case 1: return CHAT;
        case 2: return PAGE_OPEN;
        case 3: return WORLD_FRAME;
        case 4: return TOWN_FRAME;
        case 5: return BATTLE_FRAME;
        case 6: return REQUEST;
        case 7: return LOADSCENE_TIME;
        case 8: return LOADSCENE_FRAME;
        case 9: return UPDATEVER_TIME;
        case 10: return UPDATEVER_FRAME;
        case 11: return LOGINSDK_TIME;
        case 12: return LOGINSDK_FRAME;
        case 13: return SERVERLIST_TIME;
        case 14: return SERVERLIST_FRAME;
        case 15: return GRAYUPDATE_TIME;
        case 16: return GRAYUPDATE_FRAME;
        case 17: return PRELOAD_TIME;
        case 18: return PRELOAD_FRAME;
        case 19: return LOGINSERVER_TIME;
        case 20: return LOGINSERVER_FRAME;
        case 21: return GAMENEWBIE_TIME;
        case 22: return GAMENEWBIE_FRAME;
        case 23: return GAMEINTROSTATE_TIME;
        case 24: return GAMEINTROSTATE_FRAME;
        case 25: return PUSH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.Analyze.getDescriptor().getEnumTypes().get(0);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ActionType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ActionType)
  }

  public interface AnalyzeDataPBOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .ActionType action = 1;
    /**
     * <code>required .ActionType action = 1;</code>
     *
     * <pre>
     * 操作类型
     * </pre>
     */
    boolean hasAction();
    /**
     * <code>required .ActionType action = 1;</code>
     *
     * <pre>
     * 操作类型
     * </pre>
     */
    com.hawk.game.protocol.Analyze.ActionType getAction();

    // optional int32 count = 2;
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * 自上次上报之后的操作次数，不填此字段默认为1次
     * </pre>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * 自上次上报之后的操作次数，不填此字段默认为1次
     * </pre>
     */
    int getCount();

    // required int64 value = 3;
    /**
     * <code>required int64 value = 3;</code>
     *
     * <pre>
     * 总数据，统计打开页面耗时时为总时间，统计帧率的时候为帧率和
     * </pre>
     */
    boolean hasValue();
    /**
     * <code>required int64 value = 3;</code>
     *
     * <pre>
     * 总数据，统计打开页面耗时时为总时间，统计帧率的时候为帧率和
     * </pre>
     */
    long getValue();

    // optional string extra = 4;
    /**
     * <code>optional string extra = 4;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    boolean hasExtra();
    /**
     * <code>optional string extra = 4;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    java.lang.String getExtra();
    /**
     * <code>optional string extra = 4;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getExtraBytes();

    // required int64 maxValue = 5;
    /**
     * <code>required int64 maxValue = 5;</code>
     *
     * <pre>
     * 单次最大值
     * </pre>
     */
    boolean hasMaxValue();
    /**
     * <code>required int64 maxValue = 5;</code>
     *
     * <pre>
     * 单次最大值
     * </pre>
     */
    long getMaxValue();

    // required int64 minValue = 6;
    /**
     * <code>required int64 minValue = 6;</code>
     *
     * <pre>
     * 单次最小值
     * </pre>
     */
    boolean hasMinValue();
    /**
     * <code>required int64 minValue = 6;</code>
     *
     * <pre>
     * 单次最小值
     * </pre>
     */
    long getMinValue();
  }
  /**
   * Protobuf type {@code AnalyzeDataPB}
   */
  public static final class AnalyzeDataPB extends
      com.google.protobuf.GeneratedMessage
      implements AnalyzeDataPBOrBuilder {
    // Use AnalyzeDataPB.newBuilder() to construct.
    private AnalyzeDataPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AnalyzeDataPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AnalyzeDataPB defaultInstance;
    public static AnalyzeDataPB getDefaultInstance() {
      return defaultInstance;
    }

    public AnalyzeDataPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AnalyzeDataPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hawk.game.protocol.Analyze.ActionType value = com.hawk.game.protocol.Analyze.ActionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              value_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              extra_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              maxValue_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              minValue_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDataPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDataPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.Analyze.AnalyzeDataPB.class, com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder.class);
    }

    public static com.google.protobuf.Parser<AnalyzeDataPB> PARSER =
        new com.google.protobuf.AbstractParser<AnalyzeDataPB>() {
      public AnalyzeDataPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnalyzeDataPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AnalyzeDataPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .ActionType action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private com.hawk.game.protocol.Analyze.ActionType action_;
    /**
     * <code>required .ActionType action = 1;</code>
     *
     * <pre>
     * 操作类型
     * </pre>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ActionType action = 1;</code>
     *
     * <pre>
     * 操作类型
     * </pre>
     */
    public com.hawk.game.protocol.Analyze.ActionType getAction() {
      return action_;
    }

    // optional int32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * 自上次上报之后的操作次数，不填此字段默认为1次
     * </pre>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * 自上次上报之后的操作次数，不填此字段默认为1次
     * </pre>
     */
    public int getCount() {
      return count_;
    }

    // required int64 value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private long value_;
    /**
     * <code>required int64 value = 3;</code>
     *
     * <pre>
     * 总数据，统计打开页面耗时时为总时间，统计帧率的时候为帧率和
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 value = 3;</code>
     *
     * <pre>
     * 总数据，统计打开页面耗时时为总时间，统计帧率的时候为帧率和
     * </pre>
     */
    public long getValue() {
      return value_;
    }

    // optional string extra = 4;
    public static final int EXTRA_FIELD_NUMBER = 4;
    private java.lang.Object extra_;
    /**
     * <code>optional string extra = 4;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    public boolean hasExtra() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string extra = 4;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          extra_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string extra = 4;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 maxValue = 5;
    public static final int MAXVALUE_FIELD_NUMBER = 5;
    private long maxValue_;
    /**
     * <code>required int64 maxValue = 5;</code>
     *
     * <pre>
     * 单次最大值
     * </pre>
     */
    public boolean hasMaxValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 maxValue = 5;</code>
     *
     * <pre>
     * 单次最大值
     * </pre>
     */
    public long getMaxValue() {
      return maxValue_;
    }

    // required int64 minValue = 6;
    public static final int MINVALUE_FIELD_NUMBER = 6;
    private long minValue_;
    /**
     * <code>required int64 minValue = 6;</code>
     *
     * <pre>
     * 单次最小值
     * </pre>
     */
    public boolean hasMinValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 minValue = 6;</code>
     *
     * <pre>
     * 单次最小值
     * </pre>
     */
    public long getMinValue() {
      return minValue_;
    }

    private void initFields() {
      action_ = com.hawk.game.protocol.Analyze.ActionType.CHAT;
      count_ = 0;
      value_ = 0L;
      extra_ = "";
      maxValue_ = 0L;
      minValue_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getExtraBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, maxValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, minValue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getExtraBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, maxValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, minValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDataPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.Analyze.AnalyzeDataPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnalyzeDataPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDataPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDataPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.Analyze.AnalyzeDataPB.class, com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder.class);
      }

      // Construct using com.hawk.game.protocol.Analyze.AnalyzeDataPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        action_ = com.hawk.game.protocol.Analyze.ActionType.CHAT;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        extra_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        maxValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        minValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDataPB_descriptor;
      }

      public com.hawk.game.protocol.Analyze.AnalyzeDataPB getDefaultInstanceForType() {
        return com.hawk.game.protocol.Analyze.AnalyzeDataPB.getDefaultInstance();
      }

      public com.hawk.game.protocol.Analyze.AnalyzeDataPB build() {
        com.hawk.game.protocol.Analyze.AnalyzeDataPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.Analyze.AnalyzeDataPB buildPartial() {
        com.hawk.game.protocol.Analyze.AnalyzeDataPB result = new com.hawk.game.protocol.Analyze.AnalyzeDataPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.extra_ = extra_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.maxValue_ = maxValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.minValue_ = minValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.Analyze.AnalyzeDataPB) {
          return mergeFrom((com.hawk.game.protocol.Analyze.AnalyzeDataPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.Analyze.AnalyzeDataPB other) {
        if (other == com.hawk.game.protocol.Analyze.AnalyzeDataPB.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasExtra()) {
          bitField0_ |= 0x00000008;
          extra_ = other.extra_;
          onChanged();
        }
        if (other.hasMaxValue()) {
          setMaxValue(other.getMaxValue());
        }
        if (other.hasMinValue()) {
          setMinValue(other.getMinValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        if (!hasMaxValue()) {
          
          return false;
        }
        if (!hasMinValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.Analyze.AnalyzeDataPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.Analyze.AnalyzeDataPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .ActionType action = 1;
      private com.hawk.game.protocol.Analyze.ActionType action_ = com.hawk.game.protocol.Analyze.ActionType.CHAT;
      /**
       * <code>required .ActionType action = 1;</code>
       *
       * <pre>
       * 操作类型
       * </pre>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ActionType action = 1;</code>
       *
       * <pre>
       * 操作类型
       * </pre>
       */
      public com.hawk.game.protocol.Analyze.ActionType getAction() {
        return action_;
      }
      /**
       * <code>required .ActionType action = 1;</code>
       *
       * <pre>
       * 操作类型
       * </pre>
       */
      public Builder setAction(com.hawk.game.protocol.Analyze.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ActionType action = 1;</code>
       *
       * <pre>
       * 操作类型
       * </pre>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = com.hawk.game.protocol.Analyze.ActionType.CHAT;
        onChanged();
        return this;
      }

      // optional int32 count = 2;
      private int count_ ;
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * 自上次上报之后的操作次数，不填此字段默认为1次
       * </pre>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * 自上次上报之后的操作次数，不填此字段默认为1次
       * </pre>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * 自上次上报之后的操作次数，不填此字段默认为1次
       * </pre>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * 自上次上报之后的操作次数，不填此字段默认为1次
       * </pre>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      // required int64 value = 3;
      private long value_ ;
      /**
       * <code>required int64 value = 3;</code>
       *
       * <pre>
       * 总数据，统计打开页面耗时时为总时间，统计帧率的时候为帧率和
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 value = 3;</code>
       *
       * <pre>
       * 总数据，统计打开页面耗时时为总时间，统计帧率的时候为帧率和
       * </pre>
       */
      public long getValue() {
        return value_;
      }
      /**
       * <code>required int64 value = 3;</code>
       *
       * <pre>
       * 总数据，统计打开页面耗时时为总时间，统计帧率的时候为帧率和
       * </pre>
       */
      public Builder setValue(long value) {
        bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 value = 3;</code>
       *
       * <pre>
       * 总数据，统计打开页面耗时时为总时间，统计帧率的时候为帧率和
       * </pre>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0L;
        onChanged();
        return this;
      }

      // optional string extra = 4;
      private java.lang.Object extra_ = "";
      /**
       * <code>optional string extra = 4;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public boolean hasExtra() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string extra = 4;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public java.lang.String getExtra() {
        java.lang.Object ref = extra_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string extra = 4;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        java.lang.Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string extra = 4;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public Builder setExtra(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string extra = 4;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public Builder clearExtra() {
        bitField0_ = (bitField0_ & ~0x00000008);
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <code>optional string extra = 4;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        extra_ = value;
        onChanged();
        return this;
      }

      // required int64 maxValue = 5;
      private long maxValue_ ;
      /**
       * <code>required int64 maxValue = 5;</code>
       *
       * <pre>
       * 单次最大值
       * </pre>
       */
      public boolean hasMaxValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 maxValue = 5;</code>
       *
       * <pre>
       * 单次最大值
       * </pre>
       */
      public long getMaxValue() {
        return maxValue_;
      }
      /**
       * <code>required int64 maxValue = 5;</code>
       *
       * <pre>
       * 单次最大值
       * </pre>
       */
      public Builder setMaxValue(long value) {
        bitField0_ |= 0x00000010;
        maxValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 maxValue = 5;</code>
       *
       * <pre>
       * 单次最大值
       * </pre>
       */
      public Builder clearMaxValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        maxValue_ = 0L;
        onChanged();
        return this;
      }

      // required int64 minValue = 6;
      private long minValue_ ;
      /**
       * <code>required int64 minValue = 6;</code>
       *
       * <pre>
       * 单次最小值
       * </pre>
       */
      public boolean hasMinValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 minValue = 6;</code>
       *
       * <pre>
       * 单次最小值
       * </pre>
       */
      public long getMinValue() {
        return minValue_;
      }
      /**
       * <code>required int64 minValue = 6;</code>
       *
       * <pre>
       * 单次最小值
       * </pre>
       */
      public Builder setMinValue(long value) {
        bitField0_ |= 0x00000020;
        minValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 minValue = 6;</code>
       *
       * <pre>
       * 单次最小值
       * </pre>
       */
      public Builder clearMinValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        minValue_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AnalyzeDataPB)
    }

    static {
      defaultInstance = new AnalyzeDataPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AnalyzeDataPB)
  }

  public interface AnalyzeDatasOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .AnalyzeDataPB data = 1;
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    java.util.List<com.hawk.game.protocol.Analyze.AnalyzeDataPB> 
        getDataList();
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    com.hawk.game.protocol.Analyze.AnalyzeDataPB getData(int index);
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    java.util.List<? extends com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder getDataOrBuilder(
        int index);

    // optional string deviceInfo = 2;
    /**
     * <code>optional string deviceInfo = 2;</code>
     *
     * <pre>
     * 设备型号
     * </pre>
     */
    boolean hasDeviceInfo();
    /**
     * <code>optional string deviceInfo = 2;</code>
     *
     * <pre>
     * 设备型号
     * </pre>
     */
    java.lang.String getDeviceInfo();
    /**
     * <code>optional string deviceInfo = 2;</code>
     *
     * <pre>
     * 设备型号
     * </pre>
     */
    com.google.protobuf.ByteString
        getDeviceInfoBytes();

    // optional string version = 3;
    /**
     * <code>optional string version = 3;</code>
     *
     * <pre>
     * 客户端版本号如1.0_0.1
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 3;</code>
     *
     * <pre>
     * 客户端版本号如1.0_0.1
     * </pre>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 3;</code>
     *
     * <pre>
     * 客户端版本号如1.0_0.1
     * </pre>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    // optional int32 deviceLevel = 4;
    /**
     * <code>optional int32 deviceLevel = 4;</code>
     *
     * <pre>
     *设备等级
     * </pre>
     */
    boolean hasDeviceLevel();
    /**
     * <code>optional int32 deviceLevel = 4;</code>
     *
     * <pre>
     *设备等级
     * </pre>
     */
    int getDeviceLevel();
  }
  /**
   * Protobuf type {@code AnalyzeDatas}
   */
  public static final class AnalyzeDatas extends
      com.google.protobuf.GeneratedMessage
      implements AnalyzeDatasOrBuilder {
    // Use AnalyzeDatas.newBuilder() to construct.
    private AnalyzeDatas(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AnalyzeDatas(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AnalyzeDatas defaultInstance;
    public static AnalyzeDatas getDefaultInstance() {
      return defaultInstance;
    }

    public AnalyzeDatas getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AnalyzeDatas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<com.hawk.game.protocol.Analyze.AnalyzeDataPB>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readMessage(com.hawk.game.protocol.Analyze.AnalyzeDataPB.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              deviceInfo_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              version_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              deviceLevel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDatas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDatas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.Analyze.AnalyzeDatas.class, com.hawk.game.protocol.Analyze.AnalyzeDatas.Builder.class);
    }

    public static com.google.protobuf.Parser<AnalyzeDatas> PARSER =
        new com.google.protobuf.AbstractParser<AnalyzeDatas>() {
      public AnalyzeDatas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnalyzeDatas(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AnalyzeDatas> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .AnalyzeDataPB data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.hawk.game.protocol.Analyze.AnalyzeDataPB> data_;
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    public java.util.List<com.hawk.game.protocol.Analyze.AnalyzeDataPB> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    public java.util.List<? extends com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    public com.hawk.game.protocol.Analyze.AnalyzeDataPB getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .AnalyzeDataPB data = 1;</code>
     */
    public com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    // optional string deviceInfo = 2;
    public static final int DEVICEINFO_FIELD_NUMBER = 2;
    private java.lang.Object deviceInfo_;
    /**
     * <code>optional string deviceInfo = 2;</code>
     *
     * <pre>
     * 设备型号
     * </pre>
     */
    public boolean hasDeviceInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string deviceInfo = 2;</code>
     *
     * <pre>
     * 设备型号
     * </pre>
     */
    public java.lang.String getDeviceInfo() {
      java.lang.Object ref = deviceInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceInfo = 2;</code>
     *
     * <pre>
     * 设备型号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDeviceInfoBytes() {
      java.lang.Object ref = deviceInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private java.lang.Object version_;
    /**
     * <code>optional string version = 3;</code>
     *
     * <pre>
     * 客户端版本号如1.0_0.1
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string version = 3;</code>
     *
     * <pre>
     * 客户端版本号如1.0_0.1
     * </pre>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version = 3;</code>
     *
     * <pre>
     * 客户端版本号如1.0_0.1
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 deviceLevel = 4;
    public static final int DEVICELEVEL_FIELD_NUMBER = 4;
    private int deviceLevel_;
    /**
     * <code>optional int32 deviceLevel = 4;</code>
     *
     * <pre>
     *设备等级
     * </pre>
     */
    public boolean hasDeviceLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 deviceLevel = 4;</code>
     *
     * <pre>
     *设备等级
     * </pre>
     */
    public int getDeviceLevel() {
      return deviceLevel_;
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
      deviceInfo_ = "";
      version_ = "";
      deviceLevel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getDeviceInfoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getVersionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, deviceLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceInfoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getVersionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, deviceLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.Analyze.AnalyzeDatas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.Analyze.AnalyzeDatas prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnalyzeDatas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.Analyze.AnalyzeDatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDatas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDatas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.Analyze.AnalyzeDatas.class, com.hawk.game.protocol.Analyze.AnalyzeDatas.Builder.class);
      }

      // Construct using com.hawk.game.protocol.Analyze.AnalyzeDatas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        deviceInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.Analyze.internal_static_AnalyzeDatas_descriptor;
      }

      public com.hawk.game.protocol.Analyze.AnalyzeDatas getDefaultInstanceForType() {
        return com.hawk.game.protocol.Analyze.AnalyzeDatas.getDefaultInstance();
      }

      public com.hawk.game.protocol.Analyze.AnalyzeDatas build() {
        com.hawk.game.protocol.Analyze.AnalyzeDatas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.Analyze.AnalyzeDatas buildPartial() {
        com.hawk.game.protocol.Analyze.AnalyzeDatas result = new com.hawk.game.protocol.Analyze.AnalyzeDatas(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceInfo_ = deviceInfo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceLevel_ = deviceLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.Analyze.AnalyzeDatas) {
          return mergeFrom((com.hawk.game.protocol.Analyze.AnalyzeDatas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.Analyze.AnalyzeDatas other) {
        if (other == com.hawk.game.protocol.Analyze.AnalyzeDatas.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        if (other.hasDeviceInfo()) {
          bitField0_ |= 0x00000002;
          deviceInfo_ = other.deviceInfo_;
          onChanged();
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000004;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasDeviceLevel()) {
          setDeviceLevel(other.getDeviceLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.Analyze.AnalyzeDatas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.Analyze.AnalyzeDatas) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .AnalyzeDataPB data = 1;
      private java.util.List<com.hawk.game.protocol.Analyze.AnalyzeDataPB> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<com.hawk.game.protocol.Analyze.AnalyzeDataPB>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.Analyze.AnalyzeDataPB, com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder, com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder> dataBuilder_;

      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public java.util.List<com.hawk.game.protocol.Analyze.AnalyzeDataPB> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public com.hawk.game.protocol.Analyze.AnalyzeDataPB getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public Builder setData(
          int index, com.hawk.game.protocol.Analyze.AnalyzeDataPB value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public Builder setData(
          int index, com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public Builder addData(com.hawk.game.protocol.Analyze.AnalyzeDataPB value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public Builder addData(
          int index, com.hawk.game.protocol.Analyze.AnalyzeDataPB value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public Builder addData(
          com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public Builder addData(
          int index, com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.hawk.game.protocol.Analyze.AnalyzeDataPB> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public java.util.List<? extends com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.hawk.game.protocol.Analyze.AnalyzeDataPB.getDefaultInstance());
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.hawk.game.protocol.Analyze.AnalyzeDataPB.getDefaultInstance());
      }
      /**
       * <code>repeated .AnalyzeDataPB data = 1;</code>
       */
      public java.util.List<com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.Analyze.AnalyzeDataPB, com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder, com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hawk.game.protocol.Analyze.AnalyzeDataPB, com.hawk.game.protocol.Analyze.AnalyzeDataPB.Builder, com.hawk.game.protocol.Analyze.AnalyzeDataPBOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // optional string deviceInfo = 2;
      private java.lang.Object deviceInfo_ = "";
      /**
       * <code>optional string deviceInfo = 2;</code>
       *
       * <pre>
       * 设备型号
       * </pre>
       */
      public boolean hasDeviceInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string deviceInfo = 2;</code>
       *
       * <pre>
       * 设备型号
       * </pre>
       */
      public java.lang.String getDeviceInfo() {
        java.lang.Object ref = deviceInfo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceInfo = 2;</code>
       *
       * <pre>
       * 设备型号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDeviceInfoBytes() {
        java.lang.Object ref = deviceInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceInfo = 2;</code>
       *
       * <pre>
       * 设备型号
       * </pre>
       */
      public Builder setDeviceInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceInfo = 2;</code>
       *
       * <pre>
       * 设备型号
       * </pre>
       */
      public Builder clearDeviceInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceInfo_ = getDefaultInstance().getDeviceInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceInfo = 2;</code>
       *
       * <pre>
       * 设备型号
       * </pre>
       */
      public Builder setDeviceInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceInfo_ = value;
        onChanged();
        return this;
      }

      // optional string version = 3;
      private java.lang.Object version_ = "";
      /**
       * <code>optional string version = 3;</code>
       *
       * <pre>
       * 客户端版本号如1.0_0.1
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string version = 3;</code>
       *
       * <pre>
       * 客户端版本号如1.0_0.1
       * </pre>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version = 3;</code>
       *
       * <pre>
       * 客户端版本号如1.0_0.1
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 3;</code>
       *
       * <pre>
       * 客户端版本号如1.0_0.1
       * </pre>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 3;</code>
       *
       * <pre>
       * 客户端版本号如1.0_0.1
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 3;</code>
       *
       * <pre>
       * 客户端版本号如1.0_0.1
       * </pre>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }

      // optional int32 deviceLevel = 4;
      private int deviceLevel_ ;
      /**
       * <code>optional int32 deviceLevel = 4;</code>
       *
       * <pre>
       *设备等级
       * </pre>
       */
      public boolean hasDeviceLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 deviceLevel = 4;</code>
       *
       * <pre>
       *设备等级
       * </pre>
       */
      public int getDeviceLevel() {
        return deviceLevel_;
      }
      /**
       * <code>optional int32 deviceLevel = 4;</code>
       *
       * <pre>
       *设备等级
       * </pre>
       */
      public Builder setDeviceLevel(int value) {
        bitField0_ |= 0x00000008;
        deviceLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 deviceLevel = 4;</code>
       *
       * <pre>
       *设备等级
       * </pre>
       */
      public Builder clearDeviceLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceLevel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AnalyzeDatas)
    }

    static {
      defaultInstance = new AnalyzeDatas(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AnalyzeDatas)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AnalyzeDataPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AnalyzeDataPB_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AnalyzeDatas_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AnalyzeDatas_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rAnalyze.proto\"}\n\rAnalyzeDataPB\022\033\n\006acti" +
      "on\030\001 \002(\0162\013.ActionType\022\r\n\005count\030\002 \001(\005\022\r\n\005" +
      "value\030\003 \002(\003\022\r\n\005extra\030\004 \001(\t\022\020\n\010maxValue\030\005" +
      " \002(\003\022\020\n\010minValue\030\006 \002(\003\"f\n\014AnalyzeDatas\022\034" +
      "\n\004data\030\001 \003(\0132\016.AnalyzeDataPB\022\022\n\ndeviceIn" +
      "fo\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\022\023\n\013deviceLevel" +
      "\030\004 \001(\005*\356\003\n\nActionType\022\010\n\004CHAT\020\001\022\r\n\tPAGE_" +
      "OPEN\020\002\022\017\n\013WORLD_FRAME\020\003\022\016\n\nTOWN_FRAME\020\004\022" +
      "\020\n\014BATTLE_FRAME\020\005\022\013\n\007REQUEST\020\006\022\022\n\016LOADSC" +
      "ENE_TIME\020\007\022\023\n\017LOADSCENE_FRAME\020\010\022\022\n\016UPDAT",
      "EVER_TIME\020\t\022\023\n\017UPDATEVER_FRAME\020\n\022\021\n\rLOGI" +
      "NSDK_TIME\020\013\022\022\n\016LOGINSDK_FRAME\020\014\022\023\n\017SERVE" +
      "RLIST_TIME\020\r\022\024\n\020SERVERLIST_FRAME\020\016\022\023\n\017GR" +
      "AYUPDATE_TIME\020\017\022\024\n\020GRAYUPDATE_FRAME\020\020\022\020\n" +
      "\014PRELOAD_TIME\020\021\022\021\n\rPRELOAD_FRAME\020\022\022\024\n\020LO" +
      "GINSERVER_TIME\020\023\022\025\n\021LOGINSERVER_FRAME\020\024\022" +
      "\023\n\017GAMENEWBIE_TIME\020\025\022\024\n\020GAMENEWBIE_FRAME" +
      "\020\026\022\027\n\023GAMEINTROSTATE_TIME\020\027\022\030\n\024GAMEINTRO" +
      "STATE_FRAME\020\030\022\010\n\004PUSH\020\031B\030\n\026com.hawk.game" +
      ".protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_AnalyzeDataPB_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_AnalyzeDataPB_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AnalyzeDataPB_descriptor,
              new java.lang.String[] { "Action", "Count", "Value", "Extra", "MaxValue", "MinValue", });
          internal_static_AnalyzeDatas_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_AnalyzeDatas_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AnalyzeDatas_descriptor,
              new java.lang.String[] { "Data", "DeviceInfo", "Version", "DeviceLevel", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
