// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CrossTech.proto

package com.hawk.game.protocol;

public final class CrossTech {
  private CrossTech() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code LvlUpType}
   *
   * <pre>
   * 远征科技升级类型
   * </pre>
   */
  public enum LvlUpType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NORMAL = 1;</code>
     *
     * <pre>
     *普通升级
     * </pre>
     */
    NORMAL(0, 1),
    /**
     * <code>BUY_RES = 2;</code>
     *
     * <pre>
     *买资源升级
     * </pre>
     */
    BUY_RES(1, 2),
    /**
     * <code>BUY_RES_AND_TIME = 3;</code>
     *
     * <pre>
     *买资源并且秒时间
     * </pre>
     */
    BUY_RES_AND_TIME(2, 3),
    ;

    /**
     * <code>NORMAL = 1;</code>
     *
     * <pre>
     *普通升级
     * </pre>
     */
    public static final int NORMAL_VALUE = 1;
    /**
     * <code>BUY_RES = 2;</code>
     *
     * <pre>
     *买资源升级
     * </pre>
     */
    public static final int BUY_RES_VALUE = 2;
    /**
     * <code>BUY_RES_AND_TIME = 3;</code>
     *
     * <pre>
     *买资源并且秒时间
     * </pre>
     */
    public static final int BUY_RES_AND_TIME_VALUE = 3;


    public final int getNumber() { return value; }

    public static LvlUpType valueOf(int value) {
      switch (value) {
        case 1: return NORMAL;
        case 2: return BUY_RES;
        case 3: return BUY_RES_AND_TIME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LvlUpType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LvlUpType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LvlUpType>() {
            public LvlUpType findValueByNumber(int number) {
              return LvlUpType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.CrossTech.getDescriptor().getEnumTypes().get(0);
    }

    private static final LvlUpType[] VALUES = values();

    public static LvlUpType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LvlUpType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LvlUpType)
  }

  public interface HPTechnologySyncOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 techId = 1;
    /**
     * <code>repeated int32 techId = 1;</code>
     *
     * <pre>
     * 科技ID
     * </pre>
     */
    java.util.List<java.lang.Integer> getTechIdList();
    /**
     * <code>repeated int32 techId = 1;</code>
     *
     * <pre>
     * 科技ID
     * </pre>
     */
    int getTechIdCount();
    /**
     * <code>repeated int32 techId = 1;</code>
     *
     * <pre>
     * 科技ID
     * </pre>
     */
    int getTechId(int index);

    // optional int64 unlockTime = 2;
    /**
     * <code>optional int64 unlockTime = 2;</code>
     *
     * <pre>
     * 远征科技解锁时间
     * </pre>
     */
    boolean hasUnlockTime();
    /**
     * <code>optional int64 unlockTime = 2;</code>
     *
     * <pre>
     * 远征科技解锁时间
     * </pre>
     */
    long getUnlockTime();
  }
  /**
   * Protobuf type {@code HPTechnologySync}
   *
   * <pre>
   * 远征科技信息
   * </pre>
   */
  public static final class HPTechnologySync extends
      com.google.protobuf.GeneratedMessage
      implements HPTechnologySyncOrBuilder {
    // Use HPTechnologySync.newBuilder() to construct.
    private HPTechnologySync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPTechnologySync(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPTechnologySync defaultInstance;
    public static HPTechnologySync getDefaultInstance() {
      return defaultInstance;
    }

    public HPTechnologySync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPTechnologySync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                techId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              techId_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                techId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                techId_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              unlockTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          techId_ = java.util.Collections.unmodifiableList(techId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.CrossTech.internal_static_HPTechnologySync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.CrossTech.internal_static_HPTechnologySync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.CrossTech.HPTechnologySync.class, com.hawk.game.protocol.CrossTech.HPTechnologySync.Builder.class);
    }

    public static com.google.protobuf.Parser<HPTechnologySync> PARSER =
        new com.google.protobuf.AbstractParser<HPTechnologySync>() {
      public HPTechnologySync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPTechnologySync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPTechnologySync> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated int32 techId = 1;
    public static final int TECHID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> techId_;
    /**
     * <code>repeated int32 techId = 1;</code>
     *
     * <pre>
     * 科技ID
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getTechIdList() {
      return techId_;
    }
    /**
     * <code>repeated int32 techId = 1;</code>
     *
     * <pre>
     * 科技ID
     * </pre>
     */
    public int getTechIdCount() {
      return techId_.size();
    }
    /**
     * <code>repeated int32 techId = 1;</code>
     *
     * <pre>
     * 科技ID
     * </pre>
     */
    public int getTechId(int index) {
      return techId_.get(index);
    }

    // optional int64 unlockTime = 2;
    public static final int UNLOCKTIME_FIELD_NUMBER = 2;
    private long unlockTime_;
    /**
     * <code>optional int64 unlockTime = 2;</code>
     *
     * <pre>
     * 远征科技解锁时间
     * </pre>
     */
    public boolean hasUnlockTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 unlockTime = 2;</code>
     *
     * <pre>
     * 远征科技解锁时间
     * </pre>
     */
    public long getUnlockTime() {
      return unlockTime_;
    }

    private void initFields() {
      techId_ = java.util.Collections.emptyList();
      unlockTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < techId_.size(); i++) {
        output.writeInt32(1, techId_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, unlockTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < techId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(techId_.get(i));
        }
        size += dataSize;
        size += 1 * getTechIdList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, unlockTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.CrossTech.HPTechnologySync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.CrossTech.HPTechnologySync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPTechnologySync}
     *
     * <pre>
     * 远征科技信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.CrossTech.HPTechnologySyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.CrossTech.internal_static_HPTechnologySync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.CrossTech.internal_static_HPTechnologySync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.CrossTech.HPTechnologySync.class, com.hawk.game.protocol.CrossTech.HPTechnologySync.Builder.class);
      }

      // Construct using com.hawk.game.protocol.CrossTech.HPTechnologySync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        techId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        unlockTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.CrossTech.internal_static_HPTechnologySync_descriptor;
      }

      public com.hawk.game.protocol.CrossTech.HPTechnologySync getDefaultInstanceForType() {
        return com.hawk.game.protocol.CrossTech.HPTechnologySync.getDefaultInstance();
      }

      public com.hawk.game.protocol.CrossTech.HPTechnologySync build() {
        com.hawk.game.protocol.CrossTech.HPTechnologySync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.CrossTech.HPTechnologySync buildPartial() {
        com.hawk.game.protocol.CrossTech.HPTechnologySync result = new com.hawk.game.protocol.CrossTech.HPTechnologySync(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          techId_ = java.util.Collections.unmodifiableList(techId_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.techId_ = techId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unlockTime_ = unlockTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.CrossTech.HPTechnologySync) {
          return mergeFrom((com.hawk.game.protocol.CrossTech.HPTechnologySync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.CrossTech.HPTechnologySync other) {
        if (other == com.hawk.game.protocol.CrossTech.HPTechnologySync.getDefaultInstance()) return this;
        if (!other.techId_.isEmpty()) {
          if (techId_.isEmpty()) {
            techId_ = other.techId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTechIdIsMutable();
            techId_.addAll(other.techId_);
          }
          onChanged();
        }
        if (other.hasUnlockTime()) {
          setUnlockTime(other.getUnlockTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.CrossTech.HPTechnologySync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.CrossTech.HPTechnologySync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 techId = 1;
      private java.util.List<java.lang.Integer> techId_ = java.util.Collections.emptyList();
      private void ensureTechIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          techId_ = new java.util.ArrayList<java.lang.Integer>(techId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 techId = 1;</code>
       *
       * <pre>
       * 科技ID
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getTechIdList() {
        return java.util.Collections.unmodifiableList(techId_);
      }
      /**
       * <code>repeated int32 techId = 1;</code>
       *
       * <pre>
       * 科技ID
       * </pre>
       */
      public int getTechIdCount() {
        return techId_.size();
      }
      /**
       * <code>repeated int32 techId = 1;</code>
       *
       * <pre>
       * 科技ID
       * </pre>
       */
      public int getTechId(int index) {
        return techId_.get(index);
      }
      /**
       * <code>repeated int32 techId = 1;</code>
       *
       * <pre>
       * 科技ID
       * </pre>
       */
      public Builder setTechId(
          int index, int value) {
        ensureTechIdIsMutable();
        techId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 techId = 1;</code>
       *
       * <pre>
       * 科技ID
       * </pre>
       */
      public Builder addTechId(int value) {
        ensureTechIdIsMutable();
        techId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 techId = 1;</code>
       *
       * <pre>
       * 科技ID
       * </pre>
       */
      public Builder addAllTechId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTechIdIsMutable();
        super.addAll(values, techId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 techId = 1;</code>
       *
       * <pre>
       * 科技ID
       * </pre>
       */
      public Builder clearTechId() {
        techId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // optional int64 unlockTime = 2;
      private long unlockTime_ ;
      /**
       * <code>optional int64 unlockTime = 2;</code>
       *
       * <pre>
       * 远征科技解锁时间
       * </pre>
       */
      public boolean hasUnlockTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 unlockTime = 2;</code>
       *
       * <pre>
       * 远征科技解锁时间
       * </pre>
       */
      public long getUnlockTime() {
        return unlockTime_;
      }
      /**
       * <code>optional int64 unlockTime = 2;</code>
       *
       * <pre>
       * 远征科技解锁时间
       * </pre>
       */
      public Builder setUnlockTime(long value) {
        bitField0_ |= 0x00000002;
        unlockTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 unlockTime = 2;</code>
       *
       * <pre>
       * 远征科技解锁时间
       * </pre>
       */
      public Builder clearUnlockTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        unlockTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPTechnologySync)
    }

    static {
      defaultInstance = new HPTechnologySync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPTechnologySync)
  }

  public interface LevelUpTechnologyReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 techId = 1;
    /**
     * <code>required int32 techId = 1;</code>
     *
     * <pre>
     *科技ID
     * </pre>
     */
    boolean hasTechId();
    /**
     * <code>required int32 techId = 1;</code>
     *
     * <pre>
     *科技ID
     * </pre>
     */
    int getTechId();

    // required .LvlUpType type = 2;
    /**
     * <code>required .LvlUpType type = 2;</code>
     *
     * <pre>
     *是否使用水晶
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .LvlUpType type = 2;</code>
     *
     * <pre>
     *是否使用水晶
     * </pre>
     */
    com.hawk.game.protocol.CrossTech.LvlUpType getType();
  }
  /**
   * Protobuf type {@code LevelUpTechnologyReq}
   *
   * <pre>
   * 远征科技研究
   * </pre>
   */
  public static final class LevelUpTechnologyReq extends
      com.google.protobuf.GeneratedMessage
      implements LevelUpTechnologyReqOrBuilder {
    // Use LevelUpTechnologyReq.newBuilder() to construct.
    private LevelUpTechnologyReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LevelUpTechnologyReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LevelUpTechnologyReq defaultInstance;
    public static LevelUpTechnologyReq getDefaultInstance() {
      return defaultInstance;
    }

    public LevelUpTechnologyReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LevelUpTechnologyReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              techId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.hawk.game.protocol.CrossTech.LvlUpType value = com.hawk.game.protocol.CrossTech.LvlUpType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.CrossTech.internal_static_LevelUpTechnologyReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.CrossTech.internal_static_LevelUpTechnologyReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq.class, com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LevelUpTechnologyReq> PARSER =
        new com.google.protobuf.AbstractParser<LevelUpTechnologyReq>() {
      public LevelUpTechnologyReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LevelUpTechnologyReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LevelUpTechnologyReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 techId = 1;
    public static final int TECHID_FIELD_NUMBER = 1;
    private int techId_;
    /**
     * <code>required int32 techId = 1;</code>
     *
     * <pre>
     *科技ID
     * </pre>
     */
    public boolean hasTechId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 techId = 1;</code>
     *
     * <pre>
     *科技ID
     * </pre>
     */
    public int getTechId() {
      return techId_;
    }

    // required .LvlUpType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private com.hawk.game.protocol.CrossTech.LvlUpType type_;
    /**
     * <code>required .LvlUpType type = 2;</code>
     *
     * <pre>
     *是否使用水晶
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .LvlUpType type = 2;</code>
     *
     * <pre>
     *是否使用水晶
     * </pre>
     */
    public com.hawk.game.protocol.CrossTech.LvlUpType getType() {
      return type_;
    }

    private void initFields() {
      techId_ = 0;
      type_ = com.hawk.game.protocol.CrossTech.LvlUpType.NORMAL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTechId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, techId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, techId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LevelUpTechnologyReq}
     *
     * <pre>
     * 远征科技研究
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.CrossTech.LevelUpTechnologyReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.CrossTech.internal_static_LevelUpTechnologyReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.CrossTech.internal_static_LevelUpTechnologyReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq.class, com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq.Builder.class);
      }

      // Construct using com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        techId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.hawk.game.protocol.CrossTech.LvlUpType.NORMAL;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.CrossTech.internal_static_LevelUpTechnologyReq_descriptor;
      }

      public com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq getDefaultInstanceForType() {
        return com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq.getDefaultInstance();
      }

      public com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq build() {
        com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq buildPartial() {
        com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq result = new com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.techId_ = techId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq) {
          return mergeFrom((com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq other) {
        if (other == com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq.getDefaultInstance()) return this;
        if (other.hasTechId()) {
          setTechId(other.getTechId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTechId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.CrossTech.LevelUpTechnologyReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 techId = 1;
      private int techId_ ;
      /**
       * <code>required int32 techId = 1;</code>
       *
       * <pre>
       *科技ID
       * </pre>
       */
      public boolean hasTechId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 techId = 1;</code>
       *
       * <pre>
       *科技ID
       * </pre>
       */
      public int getTechId() {
        return techId_;
      }
      /**
       * <code>required int32 techId = 1;</code>
       *
       * <pre>
       *科技ID
       * </pre>
       */
      public Builder setTechId(int value) {
        bitField0_ |= 0x00000001;
        techId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 techId = 1;</code>
       *
       * <pre>
       *科技ID
       * </pre>
       */
      public Builder clearTechId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        techId_ = 0;
        onChanged();
        return this;
      }

      // required .LvlUpType type = 2;
      private com.hawk.game.protocol.CrossTech.LvlUpType type_ = com.hawk.game.protocol.CrossTech.LvlUpType.NORMAL;
      /**
       * <code>required .LvlUpType type = 2;</code>
       *
       * <pre>
       *是否使用水晶
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .LvlUpType type = 2;</code>
       *
       * <pre>
       *是否使用水晶
       * </pre>
       */
      public com.hawk.game.protocol.CrossTech.LvlUpType getType() {
        return type_;
      }
      /**
       * <code>required .LvlUpType type = 2;</code>
       *
       * <pre>
       *是否使用水晶
       * </pre>
       */
      public Builder setType(com.hawk.game.protocol.CrossTech.LvlUpType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .LvlUpType type = 2;</code>
       *
       * <pre>
       *是否使用水晶
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.hawk.game.protocol.CrossTech.LvlUpType.NORMAL;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LevelUpTechnologyReq)
    }

    static {
      defaultInstance = new LevelUpTechnologyReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LevelUpTechnologyReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPTechnologySync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPTechnologySync_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LevelUpTechnologyReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LevelUpTechnologyReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CrossTech.proto\"6\n\020HPTechnologySync\022\016\n" +
      "\006techId\030\001 \003(\005\022\022\n\nunlockTime\030\002 \001(\003\"@\n\024Lev" +
      "elUpTechnologyReq\022\016\n\006techId\030\001 \002(\005\022\030\n\004typ" +
      "e\030\002 \002(\0162\n.LvlUpType*:\n\tLvlUpType\022\n\n\006NORM" +
      "AL\020\001\022\013\n\007BUY_RES\020\002\022\024\n\020BUY_RES_AND_TIME\020\003B" +
      "\030\n\026com.hawk.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HPTechnologySync_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HPTechnologySync_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPTechnologySync_descriptor,
              new java.lang.String[] { "TechId", "UnlockTime", });
          internal_static_LevelUpTechnologyReq_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_LevelUpTechnologyReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LevelUpTechnologyReq_descriptor,
              new java.lang.String[] { "TechId", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
