// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IDIP.proto

package com.hawk.game.protocol;

public final class IDIP {
  private IDIP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code NoticeType}
   *
   * <pre>
   * 通知类型
   * </pre>
   */
  public enum NoticeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SEND_MSG = 1;</code>
     *
     * <pre>
     * 发送系统消息(弹框,手动关闭)
     * </pre>
     */
    SEND_MSG(0, 1),
    /**
     * <code>BAN_JOIN_RANK = 2;</code>
     *
     * <pre>
     * 禁止参加排行榜(提示)
     * </pre>
     */
    BAN_JOIN_RANK(1, 2),
    /**
     * <code>ZERO_EARNING = 3;</code>
     *
     * <pre>
     * 零收益(透明框提示,点击任意位置消失)
     * </pre>
     */
    ZERO_EARNING(2, 3),
    /**
     * <code>BAN_MSG = 4;</code>
     *
     * <pre>
     * 禁言(提示,带解禁时间)
     * </pre>
     */
    BAN_MSG(3, 4),
    /**
     * <code>CLEAR_CHAT_MSG = 5;</code>
     *
     * <pre>
     * 清除指定玩家聊天信息
     * </pre>
     */
    CLEAR_CHAT_MSG(4, 5),
    /**
     * <code>WORLD_CHAR_CONTROL = 6;</code>
     *
     * <pre>
     * 世界聊天控制
     * </pre>
     */
    WORLD_CHAR_CONTROL(5, 6),
    /**
     * <code>GUILD_CHAR_CONTROL = 7;</code>
     *
     * <pre>
     * 联盟聊天控制
     * </pre>
     */
    GUILD_CHAR_CONTROL(6, 7),
    /**
     * <code>KICKOUT = 8;</code>
     *
     * <pre>
     * 强制被踢下线
     * </pre>
     */
    KICKOUT(7, 8),
    /**
     * <code>YIWA_RED_POINT = 9;</code>
     *
     * <pre>
     * 伊娃红点
     * </pre>
     */
    YIWA_RED_POINT(8, 9),
    ;

    /**
     * <code>SEND_MSG = 1;</code>
     *
     * <pre>
     * 发送系统消息(弹框,手动关闭)
     * </pre>
     */
    public static final int SEND_MSG_VALUE = 1;
    /**
     * <code>BAN_JOIN_RANK = 2;</code>
     *
     * <pre>
     * 禁止参加排行榜(提示)
     * </pre>
     */
    public static final int BAN_JOIN_RANK_VALUE = 2;
    /**
     * <code>ZERO_EARNING = 3;</code>
     *
     * <pre>
     * 零收益(透明框提示,点击任意位置消失)
     * </pre>
     */
    public static final int ZERO_EARNING_VALUE = 3;
    /**
     * <code>BAN_MSG = 4;</code>
     *
     * <pre>
     * 禁言(提示,带解禁时间)
     * </pre>
     */
    public static final int BAN_MSG_VALUE = 4;
    /**
     * <code>CLEAR_CHAT_MSG = 5;</code>
     *
     * <pre>
     * 清除指定玩家聊天信息
     * </pre>
     */
    public static final int CLEAR_CHAT_MSG_VALUE = 5;
    /**
     * <code>WORLD_CHAR_CONTROL = 6;</code>
     *
     * <pre>
     * 世界聊天控制
     * </pre>
     */
    public static final int WORLD_CHAR_CONTROL_VALUE = 6;
    /**
     * <code>GUILD_CHAR_CONTROL = 7;</code>
     *
     * <pre>
     * 联盟聊天控制
     * </pre>
     */
    public static final int GUILD_CHAR_CONTROL_VALUE = 7;
    /**
     * <code>KICKOUT = 8;</code>
     *
     * <pre>
     * 强制被踢下线
     * </pre>
     */
    public static final int KICKOUT_VALUE = 8;
    /**
     * <code>YIWA_RED_POINT = 9;</code>
     *
     * <pre>
     * 伊娃红点
     * </pre>
     */
    public static final int YIWA_RED_POINT_VALUE = 9;


    public final int getNumber() { return value; }

    public static NoticeType valueOf(int value) {
      switch (value) {
        case 1: return SEND_MSG;
        case 2: return BAN_JOIN_RANK;
        case 3: return ZERO_EARNING;
        case 4: return BAN_MSG;
        case 5: return CLEAR_CHAT_MSG;
        case 6: return WORLD_CHAR_CONTROL;
        case 7: return GUILD_CHAR_CONTROL;
        case 8: return KICKOUT;
        case 9: return YIWA_RED_POINT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NoticeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<NoticeType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NoticeType>() {
            public NoticeType findValueByNumber(int number) {
              return NoticeType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.IDIP.getDescriptor().getEnumTypes().get(0);
    }

    private static final NoticeType[] VALUES = values();

    public static NoticeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private NoticeType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:NoticeType)
  }

  /**
   * Protobuf enum {@code NoticeMode}
   *
   * <pre>
   * 通知方式
   * </pre>
   */
  public enum NoticeMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 1;</code>
     *
     * <pre>
     * 无提示
     * </pre>
     */
    NONE(0, 1),
    /**
     * <code>NOTICE_MSG = 2;</code>
     *
     * <pre>
     * 提示
     * </pre>
     */
    NOTICE_MSG(1, 2),
    /**
     * <code>MSG_BOX = 3;</code>
     *
     * <pre>
     * 消息弹框
     * </pre>
     */
    MSG_BOX(2, 3),
    ;

    /**
     * <code>NONE = 1;</code>
     *
     * <pre>
     * 无提示
     * </pre>
     */
    public static final int NONE_VALUE = 1;
    /**
     * <code>NOTICE_MSG = 2;</code>
     *
     * <pre>
     * 提示
     * </pre>
     */
    public static final int NOTICE_MSG_VALUE = 2;
    /**
     * <code>MSG_BOX = 3;</code>
     *
     * <pre>
     * 消息弹框
     * </pre>
     */
    public static final int MSG_BOX_VALUE = 3;


    public final int getNumber() { return value; }

    public static NoticeMode valueOf(int value) {
      switch (value) {
        case 1: return NONE;
        case 2: return NOTICE_MSG;
        case 3: return MSG_BOX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NoticeMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<NoticeMode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NoticeMode>() {
            public NoticeMode findValueByNumber(int number) {
              return NoticeMode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.IDIP.getDescriptor().getEnumTypes().get(1);
    }

    private static final NoticeMode[] VALUES = values();

    public static NoticeMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private NoticeMode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:NoticeMode)
  }

  public interface IDIPNoticeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .NoticeType type = 1;
    /**
     * <code>required .NoticeType type = 1;</code>
     *
     * <pre>
     * 通知类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .NoticeType type = 1;</code>
     *
     * <pre>
     * 通知类型
     * </pre>
     */
    com.hawk.game.protocol.IDIP.NoticeType getType();

    // required .NoticeMode mode = 2;
    /**
     * <code>required .NoticeMode mode = 2;</code>
     *
     * <pre>
     * 通知方式
     * </pre>
     */
    boolean hasMode();
    /**
     * <code>required .NoticeMode mode = 2;</code>
     *
     * <pre>
     * 通知方式
     * </pre>
     */
    com.hawk.game.protocol.IDIP.NoticeMode getMode();

    // optional string msg = 3;
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     * 消息内容/封禁原因
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     * 消息内容/封禁原因
     * </pre>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     * 消息内容/封禁原因
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    // optional int64 relieveTime = 4;
    /**
     * <code>optional int64 relieveTime = 4;</code>
     *
     * <pre>
     * 解封时间
     * </pre>
     */
    boolean hasRelieveTime();
    /**
     * <code>optional int64 relieveTime = 4;</code>
     *
     * <pre>
     * 解封时间
     * </pre>
     */
    long getRelieveTime();

    // optional string playerId = 5;
    /**
     * <code>optional string playerId = 5;</code>
     *
     * <pre>
     * 聊天清除玩家id
     * </pre>
     */
    boolean hasPlayerId();
    /**
     * <code>optional string playerId = 5;</code>
     *
     * <pre>
     * 聊天清除玩家id
     * </pre>
     */
    java.lang.String getPlayerId();
    /**
     * <code>optional string playerId = 5;</code>
     *
     * <pre>
     * 聊天清除玩家id
     * </pre>
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();

    // optional int32 msgCode = 6;
    /**
     * <code>optional int32 msgCode = 6;</code>
     *
     * <pre>
     * 消息码
     * </pre>
     */
    boolean hasMsgCode();
    /**
     * <code>optional int32 msgCode = 6;</code>
     *
     * <pre>
     * 消息码
     * </pre>
     */
    int getMsgCode();

    // optional bool closed = 7;
    /**
     * <code>optional bool closed = 7;</code>
     *
     * <pre>
     * true: 聊天系统关闭， false: 聊天系统打开
     * </pre>
     */
    boolean hasClosed();
    /**
     * <code>optional bool closed = 7;</code>
     *
     * <pre>
     * true: 聊天系统关闭， false: 聊天系统打开
     * </pre>
     */
    boolean getClosed();
  }
  /**
   * Protobuf type {@code IDIPNotice}
   *
   * <pre>
   * IDIP提示信息	
   * </pre>
   */
  public static final class IDIPNotice extends
      com.google.protobuf.GeneratedMessage
      implements IDIPNoticeOrBuilder {
    // Use IDIPNotice.newBuilder() to construct.
    private IDIPNotice(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IDIPNotice(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IDIPNotice defaultInstance;
    public static IDIPNotice getDefaultInstance() {
      return defaultInstance;
    }

    public IDIPNotice getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IDIPNotice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hawk.game.protocol.IDIP.NoticeType value = com.hawk.game.protocol.IDIP.NoticeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.hawk.game.protocol.IDIP.NoticeMode value = com.hawk.game.protocol.IDIP.NoticeMode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                mode_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msg_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              relieveTime_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              playerId_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              msgCode_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              closed_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.IDIP.internal_static_IDIPNotice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.IDIP.internal_static_IDIPNotice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.IDIP.IDIPNotice.class, com.hawk.game.protocol.IDIP.IDIPNotice.Builder.class);
    }

    public static com.google.protobuf.Parser<IDIPNotice> PARSER =
        new com.google.protobuf.AbstractParser<IDIPNotice>() {
      public IDIPNotice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IDIPNotice(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IDIPNotice> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .NoticeType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.hawk.game.protocol.IDIP.NoticeType type_;
    /**
     * <code>required .NoticeType type = 1;</code>
     *
     * <pre>
     * 通知类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .NoticeType type = 1;</code>
     *
     * <pre>
     * 通知类型
     * </pre>
     */
    public com.hawk.game.protocol.IDIP.NoticeType getType() {
      return type_;
    }

    // required .NoticeMode mode = 2;
    public static final int MODE_FIELD_NUMBER = 2;
    private com.hawk.game.protocol.IDIP.NoticeMode mode_;
    /**
     * <code>required .NoticeMode mode = 2;</code>
     *
     * <pre>
     * 通知方式
     * </pre>
     */
    public boolean hasMode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .NoticeMode mode = 2;</code>
     *
     * <pre>
     * 通知方式
     * </pre>
     */
    public com.hawk.game.protocol.IDIP.NoticeMode getMode() {
      return mode_;
    }

    // optional string msg = 3;
    public static final int MSG_FIELD_NUMBER = 3;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     * 消息内容/封禁原因
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     * 消息内容/封禁原因
     * </pre>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 3;</code>
     *
     * <pre>
     * 消息内容/封禁原因
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 relieveTime = 4;
    public static final int RELIEVETIME_FIELD_NUMBER = 4;
    private long relieveTime_;
    /**
     * <code>optional int64 relieveTime = 4;</code>
     *
     * <pre>
     * 解封时间
     * </pre>
     */
    public boolean hasRelieveTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 relieveTime = 4;</code>
     *
     * <pre>
     * 解封时间
     * </pre>
     */
    public long getRelieveTime() {
      return relieveTime_;
    }

    // optional string playerId = 5;
    public static final int PLAYERID_FIELD_NUMBER = 5;
    private java.lang.Object playerId_;
    /**
     * <code>optional string playerId = 5;</code>
     *
     * <pre>
     * 聊天清除玩家id
     * </pre>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string playerId = 5;</code>
     *
     * <pre>
     * 聊天清除玩家id
     * </pre>
     */
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          playerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string playerId = 5;</code>
     *
     * <pre>
     * 聊天清除玩家id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 msgCode = 6;
    public static final int MSGCODE_FIELD_NUMBER = 6;
    private int msgCode_;
    /**
     * <code>optional int32 msgCode = 6;</code>
     *
     * <pre>
     * 消息码
     * </pre>
     */
    public boolean hasMsgCode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 msgCode = 6;</code>
     *
     * <pre>
     * 消息码
     * </pre>
     */
    public int getMsgCode() {
      return msgCode_;
    }

    // optional bool closed = 7;
    public static final int CLOSED_FIELD_NUMBER = 7;
    private boolean closed_;
    /**
     * <code>optional bool closed = 7;</code>
     *
     * <pre>
     * true: 聊天系统关闭， false: 聊天系统打开
     * </pre>
     */
    public boolean hasClosed() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool closed = 7;</code>
     *
     * <pre>
     * true: 聊天系统关闭， false: 聊天系统打开
     * </pre>
     */
    public boolean getClosed() {
      return closed_;
    }

    private void initFields() {
      type_ = com.hawk.game.protocol.IDIP.NoticeType.SEND_MSG;
      mode_ = com.hawk.game.protocol.IDIP.NoticeMode.NONE;
      msg_ = "";
      relieveTime_ = 0L;
      playerId_ = "";
      msgCode_ = 0;
      closed_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, relieveTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPlayerIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, msgCode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, closed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, relieveTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPlayerIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, msgCode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, closed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.IDIP.IDIPNotice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.IDIP.IDIPNotice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.IDIP.IDIPNotice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.IDIP.IDIPNotice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.IDIP.IDIPNotice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.IDIP.IDIPNotice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.IDIP.IDIPNotice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.IDIP.IDIPNotice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.IDIP.IDIPNotice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.IDIP.IDIPNotice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.IDIP.IDIPNotice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IDIPNotice}
     *
     * <pre>
     * IDIP提示信息	
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.IDIP.IDIPNoticeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.IDIP.internal_static_IDIPNotice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.IDIP.internal_static_IDIPNotice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.IDIP.IDIPNotice.class, com.hawk.game.protocol.IDIP.IDIPNotice.Builder.class);
      }

      // Construct using com.hawk.game.protocol.IDIP.IDIPNotice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.hawk.game.protocol.IDIP.NoticeType.SEND_MSG;
        bitField0_ = (bitField0_ & ~0x00000001);
        mode_ = com.hawk.game.protocol.IDIP.NoticeMode.NONE;
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        relieveTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        playerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        msgCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        closed_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.IDIP.internal_static_IDIPNotice_descriptor;
      }

      public com.hawk.game.protocol.IDIP.IDIPNotice getDefaultInstanceForType() {
        return com.hawk.game.protocol.IDIP.IDIPNotice.getDefaultInstance();
      }

      public com.hawk.game.protocol.IDIP.IDIPNotice build() {
        com.hawk.game.protocol.IDIP.IDIPNotice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.IDIP.IDIPNotice buildPartial() {
        com.hawk.game.protocol.IDIP.IDIPNotice result = new com.hawk.game.protocol.IDIP.IDIPNotice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mode_ = mode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.relieveTime_ = relieveTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgCode_ = msgCode_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.closed_ = closed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.IDIP.IDIPNotice) {
          return mergeFrom((com.hawk.game.protocol.IDIP.IDIPNotice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.IDIP.IDIPNotice other) {
        if (other == com.hawk.game.protocol.IDIP.IDIPNotice.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000004;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasRelieveTime()) {
          setRelieveTime(other.getRelieveTime());
        }
        if (other.hasPlayerId()) {
          bitField0_ |= 0x00000010;
          playerId_ = other.playerId_;
          onChanged();
        }
        if (other.hasMsgCode()) {
          setMsgCode(other.getMsgCode());
        }
        if (other.hasClosed()) {
          setClosed(other.getClosed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasMode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.IDIP.IDIPNotice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.IDIP.IDIPNotice) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .NoticeType type = 1;
      private com.hawk.game.protocol.IDIP.NoticeType type_ = com.hawk.game.protocol.IDIP.NoticeType.SEND_MSG;
      /**
       * <code>required .NoticeType type = 1;</code>
       *
       * <pre>
       * 通知类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .NoticeType type = 1;</code>
       *
       * <pre>
       * 通知类型
       * </pre>
       */
      public com.hawk.game.protocol.IDIP.NoticeType getType() {
        return type_;
      }
      /**
       * <code>required .NoticeType type = 1;</code>
       *
       * <pre>
       * 通知类型
       * </pre>
       */
      public Builder setType(com.hawk.game.protocol.IDIP.NoticeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .NoticeType type = 1;</code>
       *
       * <pre>
       * 通知类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.hawk.game.protocol.IDIP.NoticeType.SEND_MSG;
        onChanged();
        return this;
      }

      // required .NoticeMode mode = 2;
      private com.hawk.game.protocol.IDIP.NoticeMode mode_ = com.hawk.game.protocol.IDIP.NoticeMode.NONE;
      /**
       * <code>required .NoticeMode mode = 2;</code>
       *
       * <pre>
       * 通知方式
       * </pre>
       */
      public boolean hasMode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .NoticeMode mode = 2;</code>
       *
       * <pre>
       * 通知方式
       * </pre>
       */
      public com.hawk.game.protocol.IDIP.NoticeMode getMode() {
        return mode_;
      }
      /**
       * <code>required .NoticeMode mode = 2;</code>
       *
       * <pre>
       * 通知方式
       * </pre>
       */
      public Builder setMode(com.hawk.game.protocol.IDIP.NoticeMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .NoticeMode mode = 2;</code>
       *
       * <pre>
       * 通知方式
       * </pre>
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mode_ = com.hawk.game.protocol.IDIP.NoticeMode.NONE;
        onChanged();
        return this;
      }

      // optional string msg = 3;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       * 消息内容/封禁原因
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       * 消息内容/封禁原因
       * </pre>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       * 消息内容/封禁原因
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       * 消息内容/封禁原因
       * </pre>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       * 消息内容/封禁原因
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       *
       * <pre>
       * 消息内容/封禁原因
       * </pre>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }

      // optional int64 relieveTime = 4;
      private long relieveTime_ ;
      /**
       * <code>optional int64 relieveTime = 4;</code>
       *
       * <pre>
       * 解封时间
       * </pre>
       */
      public boolean hasRelieveTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 relieveTime = 4;</code>
       *
       * <pre>
       * 解封时间
       * </pre>
       */
      public long getRelieveTime() {
        return relieveTime_;
      }
      /**
       * <code>optional int64 relieveTime = 4;</code>
       *
       * <pre>
       * 解封时间
       * </pre>
       */
      public Builder setRelieveTime(long value) {
        bitField0_ |= 0x00000008;
        relieveTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 relieveTime = 4;</code>
       *
       * <pre>
       * 解封时间
       * </pre>
       */
      public Builder clearRelieveTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        relieveTime_ = 0L;
        onChanged();
        return this;
      }

      // optional string playerId = 5;
      private java.lang.Object playerId_ = "";
      /**
       * <code>optional string playerId = 5;</code>
       *
       * <pre>
       * 聊天清除玩家id
       * </pre>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string playerId = 5;</code>
       *
       * <pre>
       * 聊天清除玩家id
       * </pre>
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playerId = 5;</code>
       *
       * <pre>
       * 聊天清除玩家id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playerId = 5;</code>
       *
       * <pre>
       * 聊天清除玩家id
       * </pre>
       */
      public Builder setPlayerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerId = 5;</code>
       *
       * <pre>
       * 聊天清除玩家id
       * </pre>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        playerId_ = getDefaultInstance().getPlayerId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playerId = 5;</code>
       *
       * <pre>
       * 聊天清除玩家id
       * </pre>
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        playerId_ = value;
        onChanged();
        return this;
      }

      // optional int32 msgCode = 6;
      private int msgCode_ ;
      /**
       * <code>optional int32 msgCode = 6;</code>
       *
       * <pre>
       * 消息码
       * </pre>
       */
      public boolean hasMsgCode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 msgCode = 6;</code>
       *
       * <pre>
       * 消息码
       * </pre>
       */
      public int getMsgCode() {
        return msgCode_;
      }
      /**
       * <code>optional int32 msgCode = 6;</code>
       *
       * <pre>
       * 消息码
       * </pre>
       */
      public Builder setMsgCode(int value) {
        bitField0_ |= 0x00000020;
        msgCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msgCode = 6;</code>
       *
       * <pre>
       * 消息码
       * </pre>
       */
      public Builder clearMsgCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgCode_ = 0;
        onChanged();
        return this;
      }

      // optional bool closed = 7;
      private boolean closed_ ;
      /**
       * <code>optional bool closed = 7;</code>
       *
       * <pre>
       * true: 聊天系统关闭， false: 聊天系统打开
       * </pre>
       */
      public boolean hasClosed() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool closed = 7;</code>
       *
       * <pre>
       * true: 聊天系统关闭， false: 聊天系统打开
       * </pre>
       */
      public boolean getClosed() {
        return closed_;
      }
      /**
       * <code>optional bool closed = 7;</code>
       *
       * <pre>
       * true: 聊天系统关闭， false: 聊天系统打开
       * </pre>
       */
      public Builder setClosed(boolean value) {
        bitField0_ |= 0x00000040;
        closed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool closed = 7;</code>
       *
       * <pre>
       * true: 聊天系统关闭， false: 聊天系统打开
       * </pre>
       */
      public Builder clearClosed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        closed_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IDIPNotice)
    }

    static {
      defaultInstance = new IDIPNotice(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IDIPNotice)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IDIPNotice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IDIPNotice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nIDIP.proto\"\227\001\n\nIDIPNotice\022\031\n\004type\030\001 \002(" +
      "\0162\013.NoticeType\022\031\n\004mode\030\002 \002(\0162\013.NoticeMod" +
      "e\022\013\n\003msg\030\003 \001(\t\022\023\n\013relieveTime\030\004 \001(\003\022\020\n\010p" +
      "layerId\030\005 \001(\t\022\017\n\007msgCode\030\006 \001(\005\022\016\n\006closed" +
      "\030\007 \001(\010*\261\001\n\nNoticeType\022\014\n\010SEND_MSG\020\001\022\021\n\rB" +
      "AN_JOIN_RANK\020\002\022\020\n\014ZERO_EARNING\020\003\022\013\n\007BAN_" +
      "MSG\020\004\022\022\n\016CLEAR_CHAT_MSG\020\005\022\026\n\022WORLD_CHAR_" +
      "CONTROL\020\006\022\026\n\022GUILD_CHAR_CONTROL\020\007\022\013\n\007KIC" +
      "KOUT\020\010\022\022\n\016YIWA_RED_POINT\020\t*3\n\nNoticeMode" +
      "\022\010\n\004NONE\020\001\022\016\n\nNOTICE_MSG\020\002\022\013\n\007MSG_BOX\020\003B",
      "\030\n\026com.hawk.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_IDIPNotice_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_IDIPNotice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_IDIPNotice_descriptor,
              new java.lang.String[] { "Type", "Mode", "Msg", "RelieveTime", "PlayerId", "MsgCode", "Closed", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
