// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerProxy.proto

package com.hawk.game.protocol;

public final class ServerProxy {
  private ServerProxy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code error}
   */
  public enum error
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SERVER_NOT_FOUND = 100000;</code>
     *
     * <pre>
     * 服务器不存在
     * </pre>
     */
    SERVER_NOT_FOUND(0, 100000),
    /**
     * <code>SERVER_CONNECT_FAILED = 100001;</code>
     *
     * <pre>
     * 服务器连接失败
     * </pre>
     */
    SERVER_CONNECT_FAILED(1, 100001),
    /**
     * <code>SERVER_REQUEST_TIMEOUT = 100002;</code>
     *
     * <pre>
     * 请求超时
     * </pre>
     */
    SERVER_REQUEST_TIMEOUT(2, 100002),
    ;

    /**
     * <code>SERVER_NOT_FOUND = 100000;</code>
     *
     * <pre>
     * 服务器不存在
     * </pre>
     */
    public static final int SERVER_NOT_FOUND_VALUE = 100000;
    /**
     * <code>SERVER_CONNECT_FAILED = 100001;</code>
     *
     * <pre>
     * 服务器连接失败
     * </pre>
     */
    public static final int SERVER_CONNECT_FAILED_VALUE = 100001;
    /**
     * <code>SERVER_REQUEST_TIMEOUT = 100002;</code>
     *
     * <pre>
     * 请求超时
     * </pre>
     */
    public static final int SERVER_REQUEST_TIMEOUT_VALUE = 100002;


    public final int getNumber() { return value; }

    public static error valueOf(int value) {
      switch (value) {
        case 100000: return SERVER_NOT_FOUND;
        case 100001: return SERVER_CONNECT_FAILED;
        case 100002: return SERVER_REQUEST_TIMEOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<error>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<error>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<error>() {
            public error findValueByNumber(int number) {
              return error.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.ServerProxy.getDescriptor().getEnumTypes().get(0);
    }

    private static final error[] VALUES = values();

    public static error valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private error(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:error)
  }

  /**
   * Protobuf enum {@code code}
   */
  public enum code
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SERVER_PROXY_BASE_CMD = 100000;</code>
     *
     * <pre>
     * 跨服数据请求
     * </pre>
     */
    SERVER_PROXY_BASE_CMD(0, 100000),
    /**
     * <code>SERVER_PROXY_FETCH_WORLD = 100001;</code>
     *
     * <pre>
     * 获取跨服地图数据
     * </pre>
     */
    SERVER_PROXY_FETCH_WORLD(1, 100001),
    ;

    /**
     * <code>SERVER_PROXY_BASE_CMD = 100000;</code>
     *
     * <pre>
     * 跨服数据请求
     * </pre>
     */
    public static final int SERVER_PROXY_BASE_CMD_VALUE = 100000;
    /**
     * <code>SERVER_PROXY_FETCH_WORLD = 100001;</code>
     *
     * <pre>
     * 获取跨服地图数据
     * </pre>
     */
    public static final int SERVER_PROXY_FETCH_WORLD_VALUE = 100001;


    public final int getNumber() { return value; }

    public static code valueOf(int value) {
      switch (value) {
        case 100000: return SERVER_PROXY_BASE_CMD;
        case 100001: return SERVER_PROXY_FETCH_WORLD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<code>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<code>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<code>() {
            public code findValueByNumber(int number) {
              return code.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.ServerProxy.getDescriptor().getEnumTypes().get(1);
    }

    private static final code[] VALUES = values();

    public static code valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private code(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:code)
  }

  public interface HPProxyTestRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string reqMsg = 1;
    /**
     * <code>required string reqMsg = 1;</code>
     */
    boolean hasReqMsg();
    /**
     * <code>required string reqMsg = 1;</code>
     */
    java.lang.String getReqMsg();
    /**
     * <code>required string reqMsg = 1;</code>
     */
    com.google.protobuf.ByteString
        getReqMsgBytes();
  }
  /**
   * Protobuf type {@code HPProxyTestRequest}
   *
   * <pre>
   * 测试请求
   * </pre>
   */
  public static final class HPProxyTestRequest extends
      com.google.protobuf.GeneratedMessage
      implements HPProxyTestRequestOrBuilder {
    // Use HPProxyTestRequest.newBuilder() to construct.
    private HPProxyTestRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPProxyTestRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPProxyTestRequest defaultInstance;
    public static HPProxyTestRequest getDefaultInstance() {
      return defaultInstance;
    }

    public HPProxyTestRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPProxyTestRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              reqMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.ServerProxy.HPProxyTestRequest.class, com.hawk.game.protocol.ServerProxy.HPProxyTestRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<HPProxyTestRequest> PARSER =
        new com.google.protobuf.AbstractParser<HPProxyTestRequest>() {
      public HPProxyTestRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPProxyTestRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPProxyTestRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string reqMsg = 1;
    public static final int REQMSG_FIELD_NUMBER = 1;
    private java.lang.Object reqMsg_;
    /**
     * <code>required string reqMsg = 1;</code>
     */
    public boolean hasReqMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string reqMsg = 1;</code>
     */
    public java.lang.String getReqMsg() {
      java.lang.Object ref = reqMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reqMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string reqMsg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqMsgBytes() {
      java.lang.Object ref = reqMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      reqMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReqMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReqMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.ServerProxy.HPProxyTestRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPProxyTestRequest}
     *
     * <pre>
     * 测试请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.ServerProxy.HPProxyTestRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.ServerProxy.HPProxyTestRequest.class, com.hawk.game.protocol.ServerProxy.HPProxyTestRequest.Builder.class);
      }

      // Construct using com.hawk.game.protocol.ServerProxy.HPProxyTestRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestRequest_descriptor;
      }

      public com.hawk.game.protocol.ServerProxy.HPProxyTestRequest getDefaultInstanceForType() {
        return com.hawk.game.protocol.ServerProxy.HPProxyTestRequest.getDefaultInstance();
      }

      public com.hawk.game.protocol.ServerProxy.HPProxyTestRequest build() {
        com.hawk.game.protocol.ServerProxy.HPProxyTestRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.ServerProxy.HPProxyTestRequest buildPartial() {
        com.hawk.game.protocol.ServerProxy.HPProxyTestRequest result = new com.hawk.game.protocol.ServerProxy.HPProxyTestRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqMsg_ = reqMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.ServerProxy.HPProxyTestRequest) {
          return mergeFrom((com.hawk.game.protocol.ServerProxy.HPProxyTestRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.ServerProxy.HPProxyTestRequest other) {
        if (other == com.hawk.game.protocol.ServerProxy.HPProxyTestRequest.getDefaultInstance()) return this;
        if (other.hasReqMsg()) {
          bitField0_ |= 0x00000001;
          reqMsg_ = other.reqMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.ServerProxy.HPProxyTestRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.ServerProxy.HPProxyTestRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string reqMsg = 1;
      private java.lang.Object reqMsg_ = "";
      /**
       * <code>required string reqMsg = 1;</code>
       */
      public boolean hasReqMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string reqMsg = 1;</code>
       */
      public java.lang.String getReqMsg() {
        java.lang.Object ref = reqMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reqMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string reqMsg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReqMsgBytes() {
        java.lang.Object ref = reqMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string reqMsg = 1;</code>
       */
      public Builder setReqMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        reqMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string reqMsg = 1;</code>
       */
      public Builder clearReqMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqMsg_ = getDefaultInstance().getReqMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string reqMsg = 1;</code>
       */
      public Builder setReqMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        reqMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPProxyTestRequest)
    }

    static {
      defaultInstance = new HPProxyTestRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPProxyTestRequest)
  }

  public interface HPProxyTestResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string rspMsg = 1;
    /**
     * <code>required string rspMsg = 1;</code>
     */
    boolean hasRspMsg();
    /**
     * <code>required string rspMsg = 1;</code>
     */
    java.lang.String getRspMsg();
    /**
     * <code>required string rspMsg = 1;</code>
     */
    com.google.protobuf.ByteString
        getRspMsgBytes();
  }
  /**
   * Protobuf type {@code HPProxyTestResponse}
   *
   * <pre>
   * 测试相应
   * </pre>
   */
  public static final class HPProxyTestResponse extends
      com.google.protobuf.GeneratedMessage
      implements HPProxyTestResponseOrBuilder {
    // Use HPProxyTestResponse.newBuilder() to construct.
    private HPProxyTestResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPProxyTestResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPProxyTestResponse defaultInstance;
    public static HPProxyTestResponse getDefaultInstance() {
      return defaultInstance;
    }

    public HPProxyTestResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPProxyTestResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rspMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.ServerProxy.HPProxyTestResponse.class, com.hawk.game.protocol.ServerProxy.HPProxyTestResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<HPProxyTestResponse> PARSER =
        new com.google.protobuf.AbstractParser<HPProxyTestResponse>() {
      public HPProxyTestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPProxyTestResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPProxyTestResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string rspMsg = 1;
    public static final int RSPMSG_FIELD_NUMBER = 1;
    private java.lang.Object rspMsg_;
    /**
     * <code>required string rspMsg = 1;</code>
     */
    public boolean hasRspMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string rspMsg = 1;</code>
     */
    public java.lang.String getRspMsg() {
      java.lang.Object ref = rspMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rspMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rspMsg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRspMsgBytes() {
      java.lang.Object ref = rspMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rspMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rspMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRspMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRspMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRspMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.ServerProxy.HPProxyTestResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPProxyTestResponse}
     *
     * <pre>
     * 测试相应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.ServerProxy.HPProxyTestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.ServerProxy.HPProxyTestResponse.class, com.hawk.game.protocol.ServerProxy.HPProxyTestResponse.Builder.class);
      }

      // Construct using com.hawk.game.protocol.ServerProxy.HPProxyTestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rspMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.ServerProxy.internal_static_HPProxyTestResponse_descriptor;
      }

      public com.hawk.game.protocol.ServerProxy.HPProxyTestResponse getDefaultInstanceForType() {
        return com.hawk.game.protocol.ServerProxy.HPProxyTestResponse.getDefaultInstance();
      }

      public com.hawk.game.protocol.ServerProxy.HPProxyTestResponse build() {
        com.hawk.game.protocol.ServerProxy.HPProxyTestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.ServerProxy.HPProxyTestResponse buildPartial() {
        com.hawk.game.protocol.ServerProxy.HPProxyTestResponse result = new com.hawk.game.protocol.ServerProxy.HPProxyTestResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rspMsg_ = rspMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.ServerProxy.HPProxyTestResponse) {
          return mergeFrom((com.hawk.game.protocol.ServerProxy.HPProxyTestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.ServerProxy.HPProxyTestResponse other) {
        if (other == com.hawk.game.protocol.ServerProxy.HPProxyTestResponse.getDefaultInstance()) return this;
        if (other.hasRspMsg()) {
          bitField0_ |= 0x00000001;
          rspMsg_ = other.rspMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRspMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.ServerProxy.HPProxyTestResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.ServerProxy.HPProxyTestResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string rspMsg = 1;
      private java.lang.Object rspMsg_ = "";
      /**
       * <code>required string rspMsg = 1;</code>
       */
      public boolean hasRspMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string rspMsg = 1;</code>
       */
      public java.lang.String getRspMsg() {
        java.lang.Object ref = rspMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rspMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string rspMsg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRspMsgBytes() {
        java.lang.Object ref = rspMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rspMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rspMsg = 1;</code>
       */
      public Builder setRspMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rspMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rspMsg = 1;</code>
       */
      public Builder clearRspMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rspMsg_ = getDefaultInstance().getRspMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string rspMsg = 1;</code>
       */
      public Builder setRspMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rspMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPProxyTestResponse)
    }

    static {
      defaultInstance = new HPProxyTestResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPProxyTestResponse)
  }

  public interface ProxyFetchWorldRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 x = 1;
    /**
     * <code>required int32 x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 1;</code>
     */
    int getX();

    // required int32 y = 2;
    /**
     * <code>required int32 y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required int32 y = 2;</code>
     */
    int getY();

    // optional float speed = 3;
    /**
     * <code>optional float speed = 3;</code>
     */
    boolean hasSpeed();
    /**
     * <code>optional float speed = 3;</code>
     */
    float getSpeed();

    // required string fromServerId = 4;
    /**
     * <code>required string fromServerId = 4;</code>
     */
    boolean hasFromServerId();
    /**
     * <code>required string fromServerId = 4;</code>
     */
    java.lang.String getFromServerId();
    /**
     * <code>required string fromServerId = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromServerIdBytes();
  }
  /**
   * Protobuf type {@code ProxyFetchWorldRequest}
   *
   * <pre>
   * 跨服获取地图数据请求
   * </pre>
   */
  public static final class ProxyFetchWorldRequest extends
      com.google.protobuf.GeneratedMessage
      implements ProxyFetchWorldRequestOrBuilder {
    // Use ProxyFetchWorldRequest.newBuilder() to construct.
    private ProxyFetchWorldRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProxyFetchWorldRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProxyFetchWorldRequest defaultInstance;
    public static ProxyFetchWorldRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ProxyFetchWorldRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProxyFetchWorldRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              speed_ = input.readFloat();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              fromServerId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest.class, com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ProxyFetchWorldRequest> PARSER =
        new com.google.protobuf.AbstractParser<ProxyFetchWorldRequest>() {
      public ProxyFetchWorldRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProxyFetchWorldRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProxyFetchWorldRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>required int32 x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    // required int32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>required int32 y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    // optional float speed = 3;
    public static final int SPEED_FIELD_NUMBER = 3;
    private float speed_;
    /**
     * <code>optional float speed = 3;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float speed = 3;</code>
     */
    public float getSpeed() {
      return speed_;
    }

    // required string fromServerId = 4;
    public static final int FROMSERVERID_FIELD_NUMBER = 4;
    private java.lang.Object fromServerId_;
    /**
     * <code>required string fromServerId = 4;</code>
     */
    public boolean hasFromServerId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string fromServerId = 4;</code>
     */
    public java.lang.String getFromServerId() {
      java.lang.Object ref = fromServerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromServerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fromServerId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromServerIdBytes() {
      java.lang.Object ref = fromServerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromServerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
      speed_ = 0F;
      fromServerId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, speed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFromServerIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, speed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFromServerIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProxyFetchWorldRequest}
     *
     * <pre>
     * 跨服获取地图数据请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest.class, com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest.Builder.class);
      }

      // Construct using com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        speed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        fromServerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldRequest_descriptor;
      }

      public com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest getDefaultInstanceForType() {
        return com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest.getDefaultInstance();
      }

      public com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest build() {
        com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest buildPartial() {
        com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest result = new com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fromServerId_ = fromServerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest) {
          return mergeFrom((com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest other) {
        if (other == com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasFromServerId()) {
          bitField0_ |= 0x00000008;
          fromServerId_ = other.fromServerId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasFromServerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.ServerProxy.ProxyFetchWorldRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 x = 1;
      private int x_ ;
      /**
       * <code>required int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      // required int32 y = 2;
      private int y_ ;
      /**
       * <code>required int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      // optional float speed = 3;
      private float speed_ ;
      /**
       * <code>optional float speed = 3;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float speed = 3;</code>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>optional float speed = 3;</code>
       */
      public Builder setSpeed(float value) {
        bitField0_ |= 0x00000004;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float speed = 3;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        speed_ = 0F;
        onChanged();
        return this;
      }

      // required string fromServerId = 4;
      private java.lang.Object fromServerId_ = "";
      /**
       * <code>required string fromServerId = 4;</code>
       */
      public boolean hasFromServerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string fromServerId = 4;</code>
       */
      public java.lang.String getFromServerId() {
        java.lang.Object ref = fromServerId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fromServerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fromServerId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromServerIdBytes() {
        java.lang.Object ref = fromServerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromServerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fromServerId = 4;</code>
       */
      public Builder setFromServerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromServerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fromServerId = 4;</code>
       */
      public Builder clearFromServerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fromServerId_ = getDefaultInstance().getFromServerId();
        onChanged();
        return this;
      }
      /**
       * <code>required string fromServerId = 4;</code>
       */
      public Builder setFromServerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromServerId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProxyFetchWorldRequest)
    }

    static {
      defaultInstance = new ProxyFetchWorldRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProxyFetchWorldRequest)
  }

  public interface ProxyFetchWorldResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .WorldPointPB points = 1;
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    java.util.List<com.hawk.game.protocol.World.WorldPointPB> 
        getPointsList();
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    com.hawk.game.protocol.World.WorldPointPB getPoints(int index);
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    int getPointsCount();
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    java.util.List<? extends com.hawk.game.protocol.World.WorldPointPBOrBuilder> 
        getPointsOrBuilderList();
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    com.hawk.game.protocol.World.WorldPointPBOrBuilder getPointsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProxyFetchWorldResponse}
   *
   * <pre>
   * 跨服获取地图数据响应
   * </pre>
   */
  public static final class ProxyFetchWorldResponse extends
      com.google.protobuf.GeneratedMessage
      implements ProxyFetchWorldResponseOrBuilder {
    // Use ProxyFetchWorldResponse.newBuilder() to construct.
    private ProxyFetchWorldResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProxyFetchWorldResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProxyFetchWorldResponse defaultInstance;
    public static ProxyFetchWorldResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ProxyFetchWorldResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProxyFetchWorldResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                points_ = new java.util.ArrayList<com.hawk.game.protocol.World.WorldPointPB>();
                mutable_bitField0_ |= 0x00000001;
              }
              points_.add(input.readMessage(com.hawk.game.protocol.World.WorldPointPB.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = java.util.Collections.unmodifiableList(points_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse.class, com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ProxyFetchWorldResponse> PARSER =
        new com.google.protobuf.AbstractParser<ProxyFetchWorldResponse>() {
      public ProxyFetchWorldResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProxyFetchWorldResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProxyFetchWorldResponse> getParserForType() {
      return PARSER;
    }

    // repeated .WorldPointPB points = 1;
    public static final int POINTS_FIELD_NUMBER = 1;
    private java.util.List<com.hawk.game.protocol.World.WorldPointPB> points_;
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    public java.util.List<com.hawk.game.protocol.World.WorldPointPB> getPointsList() {
      return points_;
    }
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    public java.util.List<? extends com.hawk.game.protocol.World.WorldPointPBOrBuilder> 
        getPointsOrBuilderList() {
      return points_;
    }
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    public com.hawk.game.protocol.World.WorldPointPB getPoints(int index) {
      return points_.get(index);
    }
    /**
     * <code>repeated .WorldPointPB points = 1;</code>
     */
    public com.hawk.game.protocol.World.WorldPointPBOrBuilder getPointsOrBuilder(
        int index) {
      return points_.get(index);
    }

    private void initFields() {
      points_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPointsCount(); i++) {
        if (!getPoints(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < points_.size(); i++) {
        output.writeMessage(1, points_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < points_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, points_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProxyFetchWorldResponse}
     *
     * <pre>
     * 跨服获取地图数据响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse.class, com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse.Builder.class);
      }

      // Construct using com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPointsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.ServerProxy.internal_static_ProxyFetchWorldResponse_descriptor;
      }

      public com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse getDefaultInstanceForType() {
        return com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse.getDefaultInstance();
      }

      public com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse build() {
        com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse buildPartial() {
        com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse result = new com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse(this);
        int from_bitField0_ = bitField0_;
        if (pointsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            points_ = java.util.Collections.unmodifiableList(points_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.points_ = points_;
        } else {
          result.points_ = pointsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse) {
          return mergeFrom((com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse other) {
        if (other == com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse.getDefaultInstance()) return this;
        if (pointsBuilder_ == null) {
          if (!other.points_.isEmpty()) {
            if (points_.isEmpty()) {
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePointsIsMutable();
              points_.addAll(other.points_);
            }
            onChanged();
          }
        } else {
          if (!other.points_.isEmpty()) {
            if (pointsBuilder_.isEmpty()) {
              pointsBuilder_.dispose();
              pointsBuilder_ = null;
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pointsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPointsFieldBuilder() : null;
            } else {
              pointsBuilder_.addAllMessages(other.points_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPointsCount(); i++) {
          if (!getPoints(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.ServerProxy.ProxyFetchWorldResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .WorldPointPB points = 1;
      private java.util.List<com.hawk.game.protocol.World.WorldPointPB> points_ =
        java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = new java.util.ArrayList<com.hawk.game.protocol.World.WorldPointPB>(points_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.World.WorldPointPB, com.hawk.game.protocol.World.WorldPointPB.Builder, com.hawk.game.protocol.World.WorldPointPBOrBuilder> pointsBuilder_;

      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public java.util.List<com.hawk.game.protocol.World.WorldPointPB> getPointsList() {
        if (pointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(points_);
        } else {
          return pointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public int getPointsCount() {
        if (pointsBuilder_ == null) {
          return points_.size();
        } else {
          return pointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public com.hawk.game.protocol.World.WorldPointPB getPoints(int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);
        } else {
          return pointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public Builder setPoints(
          int index, com.hawk.game.protocol.World.WorldPointPB value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.set(index, value);
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public Builder setPoints(
          int index, com.hawk.game.protocol.World.WorldPointPB.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public Builder addPoints(com.hawk.game.protocol.World.WorldPointPB value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public Builder addPoints(
          int index, com.hawk.game.protocol.World.WorldPointPB value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(index, value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public Builder addPoints(
          com.hawk.game.protocol.World.WorldPointPB.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public Builder addPoints(
          int index, com.hawk.game.protocol.World.WorldPointPB.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public Builder addAllPoints(
          java.lang.Iterable<? extends com.hawk.game.protocol.World.WorldPointPB> values) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          super.addAll(values, points_);
          onChanged();
        } else {
          pointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public Builder clearPoints() {
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public Builder removePoints(int index) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.remove(index);
          onChanged();
        } else {
          pointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public com.hawk.game.protocol.World.WorldPointPB.Builder getPointsBuilder(
          int index) {
        return getPointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public com.hawk.game.protocol.World.WorldPointPBOrBuilder getPointsOrBuilder(
          int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);  } else {
          return pointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public java.util.List<? extends com.hawk.game.protocol.World.WorldPointPBOrBuilder> 
           getPointsOrBuilderList() {
        if (pointsBuilder_ != null) {
          return pointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(points_);
        }
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public com.hawk.game.protocol.World.WorldPointPB.Builder addPointsBuilder() {
        return getPointsFieldBuilder().addBuilder(
            com.hawk.game.protocol.World.WorldPointPB.getDefaultInstance());
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public com.hawk.game.protocol.World.WorldPointPB.Builder addPointsBuilder(
          int index) {
        return getPointsFieldBuilder().addBuilder(
            index, com.hawk.game.protocol.World.WorldPointPB.getDefaultInstance());
      }
      /**
       * <code>repeated .WorldPointPB points = 1;</code>
       */
      public java.util.List<com.hawk.game.protocol.World.WorldPointPB.Builder> 
           getPointsBuilderList() {
        return getPointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.World.WorldPointPB, com.hawk.game.protocol.World.WorldPointPB.Builder, com.hawk.game.protocol.World.WorldPointPBOrBuilder> 
          getPointsFieldBuilder() {
        if (pointsBuilder_ == null) {
          pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hawk.game.protocol.World.WorldPointPB, com.hawk.game.protocol.World.WorldPointPB.Builder, com.hawk.game.protocol.World.WorldPointPBOrBuilder>(
                  points_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          points_ = null;
        }
        return pointsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProxyFetchWorldResponse)
    }

    static {
      defaultInstance = new ProxyFetchWorldResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProxyFetchWorldResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPProxyTestRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPProxyTestRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPProxyTestResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPProxyTestResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProxyFetchWorldRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProxyFetchWorldRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProxyFetchWorldResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProxyFetchWorldResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ServerProxy.proto\032\013World.proto\"$\n\022HPPr" +
      "oxyTestRequest\022\016\n\006reqMsg\030\001 \002(\t\"%\n\023HPProx" +
      "yTestResponse\022\016\n\006rspMsg\030\001 \002(\t\"S\n\026ProxyFe" +
      "tchWorldRequest\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005\022\r\n" +
      "\005speed\030\003 \001(\002\022\024\n\014fromServerId\030\004 \002(\t\"8\n\027Pr" +
      "oxyFetchWorldResponse\022\035\n\006points\030\001 \003(\0132\r." +
      "WorldPointPB*Z\n\005error\022\026\n\020SERVER_NOT_FOUN" +
      "D\020\240\215\006\022\033\n\025SERVER_CONNECT_FAILED\020\241\215\006\022\034\n\026SE" +
      "RVER_REQUEST_TIMEOUT\020\242\215\006*C\n\004code\022\033\n\025SERV" +
      "ER_PROXY_BASE_CMD\020\240\215\006\022\036\n\030SERVER_PROXY_FE",
      "TCH_WORLD\020\241\215\006B\030\n\026com.hawk.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HPProxyTestRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HPProxyTestRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPProxyTestRequest_descriptor,
              new java.lang.String[] { "ReqMsg", });
          internal_static_HPProxyTestResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HPProxyTestResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPProxyTestResponse_descriptor,
              new java.lang.String[] { "RspMsg", });
          internal_static_ProxyFetchWorldRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ProxyFetchWorldRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProxyFetchWorldRequest_descriptor,
              new java.lang.String[] { "X", "Y", "Speed", "FromServerId", });
          internal_static_ProxyFetchWorldResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ProxyFetchWorldResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProxyFetchWorldResponse_descriptor,
              new java.lang.String[] { "Points", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hawk.game.protocol.World.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
