// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StrengthenGuide.proto

package com.hawk.game.protocol;

public final class StrengthenGuide {
  private StrengthenGuide() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code StrengthenGuideType}
   */
  public enum StrengthenGuideType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Building = 1;</code>
     *
     * <pre>
     *城建
     * </pre>
     */
    Building(0, 1),
    /**
     * <code>Army = 2;</code>
     *
     * <pre>
     *士兵
     * </pre>
     */
    Army(1, 2),
    /**
     * <code>Commander = 3;</code>
     *
     * <pre>
     *指挥官成就和战略点
     * </pre>
     */
    Commander(2, 3),
    /**
     * <code>Science = 4;</code>
     *
     * <pre>
     *科技
     * </pre>
     */
    Science(3, 4),
    /**
     * <code>Hero = 5;</code>
     *
     * <pre>
     *英雄
     * </pre>
     */
    Hero(4, 5),
    /**
     * <code>Total = 25;</code>
     *
     * <pre>
     *总榜
     * </pre>
     */
    Total(5, 25),
    ;

    /**
     * <code>Building = 1;</code>
     *
     * <pre>
     *城建
     * </pre>
     */
    public static final int Building_VALUE = 1;
    /**
     * <code>Army = 2;</code>
     *
     * <pre>
     *士兵
     * </pre>
     */
    public static final int Army_VALUE = 2;
    /**
     * <code>Commander = 3;</code>
     *
     * <pre>
     *指挥官成就和战略点
     * </pre>
     */
    public static final int Commander_VALUE = 3;
    /**
     * <code>Science = 4;</code>
     *
     * <pre>
     *科技
     * </pre>
     */
    public static final int Science_VALUE = 4;
    /**
     * <code>Hero = 5;</code>
     *
     * <pre>
     *英雄
     * </pre>
     */
    public static final int Hero_VALUE = 5;
    /**
     * <code>Total = 25;</code>
     *
     * <pre>
     *总榜
     * </pre>
     */
    public static final int Total_VALUE = 25;


    public final int getNumber() { return value; }

    public static StrengthenGuideType valueOf(int value) {
      switch (value) {
        case 1: return Building;
        case 2: return Army;
        case 3: return Commander;
        case 4: return Science;
        case 5: return Hero;
        case 25: return Total;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StrengthenGuideType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StrengthenGuideType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StrengthenGuideType>() {
            public StrengthenGuideType findValueByNumber(int number) {
              return StrengthenGuideType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.StrengthenGuide.getDescriptor().getEnumTypes().get(0);
    }

    private static final StrengthenGuideType[] VALUES = values();

    public static StrengthenGuideType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private StrengthenGuideType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:StrengthenGuideType)
  }

  /**
   * Protobuf enum {@code StrengthenGuideOtherIDType}
   *
   * <pre>
   *配置表 stronger_method_other.xml id 字段枚举
   * </pre>
   */
  public enum StrengthenGuideOtherIDType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HeroPurpleCount = 1;</code>
     *
     * <pre>
     *紫色英雄数量
     * </pre>
     */
    HeroPurpleCount(0, 1),
    /**
     * <code>HeroOrangeCount = 2;</code>
     *
     * <pre>
     *橙色英雄数量
     * </pre>
     */
    HeroOrangeCount(1, 2),
    /**
     * <code>HeroLevelCount = 3;</code>
     *
     * <pre>
     *英雄总等级
     * </pre>
     */
    HeroLevelCount(2, 3),
    /**
     * <code>HeroStarCount = 4;</code>
     *
     * <pre>
     *英雄总星级
     * </pre>
     */
    HeroStarCount(3, 4),
    /**
     * <code>ScienceArms = 5;</code>
     *
     * <pre>
     *科技 军事总点数
     * </pre>
     */
    ScienceArms(4, 5),
    /**
     * <code>ScienceDevelop = 6;</code>
     *
     * <pre>
     *科技 发展总点数
     * </pre>
     */
    ScienceDevelop(5, 6),
    /**
     * <code>ScienceRes = 7;</code>
     *
     * <pre>
     *科技 资源总点数
     * </pre>
     */
    ScienceRes(6, 7),
    /**
     * <code>ScienceDefence = 8;</code>
     *
     * <pre>
     *科技 城防总店出
     * </pre>
     */
    ScienceDefence(7, 8),
    /**
     * <code>TalentPoints = 9;</code>
     *
     * <pre>
     *战略 获取的总点数
     * </pre>
     */
    TalentPoints(8, 9),
    /**
     * <code>TalentClasses = 10;</code>
     *
     * <pre>
     *战略 解锁的总页签
     * </pre>
     */
    TalentClasses(9, 10),
    /**
     * <code>TalentAchieve = 11;</code>
     *
     * <pre>
     *战略 成就总点数
     * </pre>
     */
    TalentAchieve(10, 11),
    ;

    /**
     * <code>HeroPurpleCount = 1;</code>
     *
     * <pre>
     *紫色英雄数量
     * </pre>
     */
    public static final int HeroPurpleCount_VALUE = 1;
    /**
     * <code>HeroOrangeCount = 2;</code>
     *
     * <pre>
     *橙色英雄数量
     * </pre>
     */
    public static final int HeroOrangeCount_VALUE = 2;
    /**
     * <code>HeroLevelCount = 3;</code>
     *
     * <pre>
     *英雄总等级
     * </pre>
     */
    public static final int HeroLevelCount_VALUE = 3;
    /**
     * <code>HeroStarCount = 4;</code>
     *
     * <pre>
     *英雄总星级
     * </pre>
     */
    public static final int HeroStarCount_VALUE = 4;
    /**
     * <code>ScienceArms = 5;</code>
     *
     * <pre>
     *科技 军事总点数
     * </pre>
     */
    public static final int ScienceArms_VALUE = 5;
    /**
     * <code>ScienceDevelop = 6;</code>
     *
     * <pre>
     *科技 发展总点数
     * </pre>
     */
    public static final int ScienceDevelop_VALUE = 6;
    /**
     * <code>ScienceRes = 7;</code>
     *
     * <pre>
     *科技 资源总点数
     * </pre>
     */
    public static final int ScienceRes_VALUE = 7;
    /**
     * <code>ScienceDefence = 8;</code>
     *
     * <pre>
     *科技 城防总店出
     * </pre>
     */
    public static final int ScienceDefence_VALUE = 8;
    /**
     * <code>TalentPoints = 9;</code>
     *
     * <pre>
     *战略 获取的总点数
     * </pre>
     */
    public static final int TalentPoints_VALUE = 9;
    /**
     * <code>TalentClasses = 10;</code>
     *
     * <pre>
     *战略 解锁的总页签
     * </pre>
     */
    public static final int TalentClasses_VALUE = 10;
    /**
     * <code>TalentAchieve = 11;</code>
     *
     * <pre>
     *战略 成就总点数
     * </pre>
     */
    public static final int TalentAchieve_VALUE = 11;


    public final int getNumber() { return value; }

    public static StrengthenGuideOtherIDType valueOf(int value) {
      switch (value) {
        case 1: return HeroPurpleCount;
        case 2: return HeroOrangeCount;
        case 3: return HeroLevelCount;
        case 4: return HeroStarCount;
        case 5: return ScienceArms;
        case 6: return ScienceDevelop;
        case 7: return ScienceRes;
        case 8: return ScienceDefence;
        case 9: return TalentPoints;
        case 10: return TalentClasses;
        case 11: return TalentAchieve;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StrengthenGuideOtherIDType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StrengthenGuideOtherIDType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StrengthenGuideOtherIDType>() {
            public StrengthenGuideOtherIDType findValueByNumber(int number) {
              return StrengthenGuideOtherIDType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.StrengthenGuide.getDescriptor().getEnumTypes().get(1);
    }

    private static final StrengthenGuideOtherIDType[] VALUES = values();

    public static StrengthenGuideOtherIDType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private StrengthenGuideOtherIDType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:StrengthenGuideOtherIDType)
  }

  /**
   * Protobuf enum {@code HeroQualityColorType}
   */
  public enum HeroQualityColorType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>White = 1;</code>
     */
    White(0, 1),
    /**
     * <code>Green = 2;</code>
     */
    Green(1, 2),
    /**
     * <code>Blue = 3;</code>
     */
    Blue(2, 3),
    /**
     * <code>Purple = 4;</code>
     */
    Purple(3, 4),
    /**
     * <code>Orange = 5;</code>
     */
    Orange(4, 5),
    ;

    /**
     * <code>White = 1;</code>
     */
    public static final int White_VALUE = 1;
    /**
     * <code>Green = 2;</code>
     */
    public static final int Green_VALUE = 2;
    /**
     * <code>Blue = 3;</code>
     */
    public static final int Blue_VALUE = 3;
    /**
     * <code>Purple = 4;</code>
     */
    public static final int Purple_VALUE = 4;
    /**
     * <code>Orange = 5;</code>
     */
    public static final int Orange_VALUE = 5;


    public final int getNumber() { return value; }

    public static HeroQualityColorType valueOf(int value) {
      switch (value) {
        case 1: return White;
        case 2: return Green;
        case 3: return Blue;
        case 4: return Purple;
        case 5: return Orange;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HeroQualityColorType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<HeroQualityColorType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HeroQualityColorType>() {
            public HeroQualityColorType findValueByNumber(int number) {
              return HeroQualityColorType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.StrengthenGuide.getDescriptor().getEnumTypes().get(2);
    }

    private static final HeroQualityColorType[] VALUES = values();

    public static HeroQualityColorType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private HeroQualityColorType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:HeroQualityColorType)
  }

  /**
   * Protobuf enum {@code TechClassType}
   */
  public enum TechClassType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Res = 1;</code>
     *
     * <pre>
     *资源
     * </pre>
     */
    Res(0, 1),
    /**
     * <code>Develop = 2;</code>
     *
     * <pre>
     *发展
     * </pre>
     */
    Develop(1, 2),
    /**
     * <code>Defence = 3;</code>
     *
     * <pre>
     *城防
     * </pre>
     */
    Defence(2, 3),
    /**
     * <code>Arms = 5;</code>
     *
     * <pre>
     *军事
     * </pre>
     */
    Arms(3, 5),
    ;

    /**
     * <code>Res = 1;</code>
     *
     * <pre>
     *资源
     * </pre>
     */
    public static final int Res_VALUE = 1;
    /**
     * <code>Develop = 2;</code>
     *
     * <pre>
     *发展
     * </pre>
     */
    public static final int Develop_VALUE = 2;
    /**
     * <code>Defence = 3;</code>
     *
     * <pre>
     *城防
     * </pre>
     */
    public static final int Defence_VALUE = 3;
    /**
     * <code>Arms = 5;</code>
     *
     * <pre>
     *军事
     * </pre>
     */
    public static final int Arms_VALUE = 5;


    public final int getNumber() { return value; }

    public static TechClassType valueOf(int value) {
      switch (value) {
        case 1: return Res;
        case 2: return Develop;
        case 3: return Defence;
        case 5: return Arms;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TechClassType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TechClassType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TechClassType>() {
            public TechClassType findValueByNumber(int number) {
              return TechClassType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.StrengthenGuide.getDescriptor().getEnumTypes().get(3);
    }

    private static final TechClassType[] VALUES = values();

    public static TechClassType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TechClassType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TechClassType)
  }

  public interface StrengthenGuideInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .StrengthenGuideType sType = 1;
    /**
     * <code>required .StrengthenGuideType sType = 1;</code>
     */
    boolean hasSType();
    /**
     * <code>required .StrengthenGuideType sType = 1;</code>
     */
    com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType getSType();

    // required int32 stageVal = 2;
    /**
     * <code>required int32 stageVal = 2;</code>
     *
     * <pre>
     *全服平均值 0 ~ 10000
     * </pre>
     */
    boolean hasStageVal();
    /**
     * <code>required int32 stageVal = 2;</code>
     *
     * <pre>
     *全服平均值 0 ~ 10000
     * </pre>
     */
    int getStageVal();

    // required int32 myStageVal = 3;
    /**
     * <code>required int32 myStageVal = 3;</code>
     *
     * <pre>
     *自己所在分段战胜万分比 0~10000
     * </pre>
     */
    boolean hasMyStageVal();
    /**
     * <code>required int32 myStageVal = 3;</code>
     *
     * <pre>
     *自己所在分段战胜万分比 0~10000
     * </pre>
     */
    int getMyStageVal();
  }
  /**
   * Protobuf type {@code StrengthenGuideInfo}
   */
  public static final class StrengthenGuideInfo extends
      com.google.protobuf.GeneratedMessage
      implements StrengthenGuideInfoOrBuilder {
    // Use StrengthenGuideInfo.newBuilder() to construct.
    private StrengthenGuideInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StrengthenGuideInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StrengthenGuideInfo defaultInstance;
    public static StrengthenGuideInfo getDefaultInstance() {
      return defaultInstance;
    }

    public StrengthenGuideInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StrengthenGuideInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType value = com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                sType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              stageVal_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              myStageVal_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.class, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<StrengthenGuideInfo> PARSER =
        new com.google.protobuf.AbstractParser<StrengthenGuideInfo>() {
      public StrengthenGuideInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StrengthenGuideInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StrengthenGuideInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .StrengthenGuideType sType = 1;
    public static final int STYPE_FIELD_NUMBER = 1;
    private com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType sType_;
    /**
     * <code>required .StrengthenGuideType sType = 1;</code>
     */
    public boolean hasSType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .StrengthenGuideType sType = 1;</code>
     */
    public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType getSType() {
      return sType_;
    }

    // required int32 stageVal = 2;
    public static final int STAGEVAL_FIELD_NUMBER = 2;
    private int stageVal_;
    /**
     * <code>required int32 stageVal = 2;</code>
     *
     * <pre>
     *全服平均值 0 ~ 10000
     * </pre>
     */
    public boolean hasStageVal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 stageVal = 2;</code>
     *
     * <pre>
     *全服平均值 0 ~ 10000
     * </pre>
     */
    public int getStageVal() {
      return stageVal_;
    }

    // required int32 myStageVal = 3;
    public static final int MYSTAGEVAL_FIELD_NUMBER = 3;
    private int myStageVal_;
    /**
     * <code>required int32 myStageVal = 3;</code>
     *
     * <pre>
     *自己所在分段战胜万分比 0~10000
     * </pre>
     */
    public boolean hasMyStageVal() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 myStageVal = 3;</code>
     *
     * <pre>
     *自己所在分段战胜万分比 0~10000
     * </pre>
     */
    public int getMyStageVal() {
      return myStageVal_;
    }

    private void initFields() {
      sType_ = com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType.Building;
      stageVal_ = 0;
      myStageVal_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStageVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMyStageVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, sType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, stageVal_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, myStageVal_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, sType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, stageVal_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, myStageVal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StrengthenGuideInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.class, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder.class);
      }

      // Construct using com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sType_ = com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType.Building;
        bitField0_ = (bitField0_ & ~0x00000001);
        stageVal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        myStageVal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfo_descriptor;
      }

      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo getDefaultInstanceForType() {
        return com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.getDefaultInstance();
      }

      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo build() {
        com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo buildPartial() {
        com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo result = new com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sType_ = sType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stageVal_ = stageVal_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.myStageVal_ = myStageVal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo) {
          return mergeFrom((com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo other) {
        if (other == com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.getDefaultInstance()) return this;
        if (other.hasSType()) {
          setSType(other.getSType());
        }
        if (other.hasStageVal()) {
          setStageVal(other.getStageVal());
        }
        if (other.hasMyStageVal()) {
          setMyStageVal(other.getMyStageVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSType()) {
          
          return false;
        }
        if (!hasStageVal()) {
          
          return false;
        }
        if (!hasMyStageVal()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .StrengthenGuideType sType = 1;
      private com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType sType_ = com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType.Building;
      /**
       * <code>required .StrengthenGuideType sType = 1;</code>
       */
      public boolean hasSType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .StrengthenGuideType sType = 1;</code>
       */
      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType getSType() {
        return sType_;
      }
      /**
       * <code>required .StrengthenGuideType sType = 1;</code>
       */
      public Builder setSType(com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        sType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .StrengthenGuideType sType = 1;</code>
       */
      public Builder clearSType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sType_ = com.hawk.game.protocol.StrengthenGuide.StrengthenGuideType.Building;
        onChanged();
        return this;
      }

      // required int32 stageVal = 2;
      private int stageVal_ ;
      /**
       * <code>required int32 stageVal = 2;</code>
       *
       * <pre>
       *全服平均值 0 ~ 10000
       * </pre>
       */
      public boolean hasStageVal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 stageVal = 2;</code>
       *
       * <pre>
       *全服平均值 0 ~ 10000
       * </pre>
       */
      public int getStageVal() {
        return stageVal_;
      }
      /**
       * <code>required int32 stageVal = 2;</code>
       *
       * <pre>
       *全服平均值 0 ~ 10000
       * </pre>
       */
      public Builder setStageVal(int value) {
        bitField0_ |= 0x00000002;
        stageVal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 stageVal = 2;</code>
       *
       * <pre>
       *全服平均值 0 ~ 10000
       * </pre>
       */
      public Builder clearStageVal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stageVal_ = 0;
        onChanged();
        return this;
      }

      // required int32 myStageVal = 3;
      private int myStageVal_ ;
      /**
       * <code>required int32 myStageVal = 3;</code>
       *
       * <pre>
       *自己所在分段战胜万分比 0~10000
       * </pre>
       */
      public boolean hasMyStageVal() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 myStageVal = 3;</code>
       *
       * <pre>
       *自己所在分段战胜万分比 0~10000
       * </pre>
       */
      public int getMyStageVal() {
        return myStageVal_;
      }
      /**
       * <code>required int32 myStageVal = 3;</code>
       *
       * <pre>
       *自己所在分段战胜万分比 0~10000
       * </pre>
       */
      public Builder setMyStageVal(int value) {
        bitField0_ |= 0x00000004;
        myStageVal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 myStageVal = 3;</code>
       *
       * <pre>
       *自己所在分段战胜万分比 0~10000
       * </pre>
       */
      public Builder clearMyStageVal() {
        bitField0_ = (bitField0_ & ~0x00000004);
        myStageVal_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:StrengthenGuideInfo)
    }

    static {
      defaultInstance = new StrengthenGuideInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StrengthenGuideInfo)
  }

  public interface StrengthenGuideInfoResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .StrengthenGuideInfo infos = 1;
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    java.util.List<com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo> 
        getInfosList();
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo getInfos(int index);
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    java.util.List<? extends com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder> 
        getInfosOrBuilderList();
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder getInfosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code StrengthenGuideInfoRes}
   */
  public static final class StrengthenGuideInfoRes extends
      com.google.protobuf.GeneratedMessage
      implements StrengthenGuideInfoResOrBuilder {
    // Use StrengthenGuideInfoRes.newBuilder() to construct.
    private StrengthenGuideInfoRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StrengthenGuideInfoRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StrengthenGuideInfoRes defaultInstance;
    public static StrengthenGuideInfoRes getDefaultInstance() {
      return defaultInstance;
    }

    public StrengthenGuideInfoRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StrengthenGuideInfoRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                infos_ = new java.util.ArrayList<com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              infos_.add(input.readMessage(com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfoRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfoRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes.class, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes.Builder.class);
    }

    public static com.google.protobuf.Parser<StrengthenGuideInfoRes> PARSER =
        new com.google.protobuf.AbstractParser<StrengthenGuideInfoRes>() {
      public StrengthenGuideInfoRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StrengthenGuideInfoRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StrengthenGuideInfoRes> getParserForType() {
      return PARSER;
    }

    // repeated .StrengthenGuideInfo infos = 1;
    public static final int INFOS_FIELD_NUMBER = 1;
    private java.util.List<com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo> infos_;
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    public java.util.List<com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo> getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    public java.util.List<? extends com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder> 
        getInfosOrBuilderList() {
      return infos_;
    }
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated .StrengthenGuideInfo infos = 1;</code>
     */
    public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder getInfosOrBuilder(
        int index) {
      return infos_.get(index);
    }

    private void initFields() {
      infos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getInfosCount(); i++) {
        if (!getInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < infos_.size(); i++) {
        output.writeMessage(1, infos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < infos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, infos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StrengthenGuideInfoRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfoRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfoRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes.class, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes.Builder.class);
      }

      // Construct using com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          infosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.StrengthenGuide.internal_static_StrengthenGuideInfoRes_descriptor;
      }

      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes getDefaultInstanceForType() {
        return com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes.getDefaultInstance();
      }

      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes build() {
        com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes buildPartial() {
        com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes result = new com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes(this);
        int from_bitField0_ = bitField0_;
        if (infosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            infos_ = java.util.Collections.unmodifiableList(infos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.infos_ = infos_;
        } else {
          result.infos_ = infosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes) {
          return mergeFrom((com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes other) {
        if (other == com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes.getDefaultInstance()) return this;
        if (infosBuilder_ == null) {
          if (!other.infos_.isEmpty()) {
            if (infos_.isEmpty()) {
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInfosIsMutable();
              infos_.addAll(other.infos_);
            }
            onChanged();
          }
        } else {
          if (!other.infos_.isEmpty()) {
            if (infosBuilder_.isEmpty()) {
              infosBuilder_.dispose();
              infosBuilder_ = null;
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              infosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfosFieldBuilder() : null;
            } else {
              infosBuilder_.addAllMessages(other.infos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getInfosCount(); i++) {
          if (!getInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .StrengthenGuideInfo infos = 1;
      private java.util.List<com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo> infos_ =
        java.util.Collections.emptyList();
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          infos_ = new java.util.ArrayList<com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo>(infos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder> infosBuilder_;

      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public java.util.List<com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo> getInfosList() {
        if (infosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(infos_);
        } else {
          return infosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public int getInfosCount() {
        if (infosBuilder_ == null) {
          return infos_.size();
        } else {
          return infosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo getInfos(int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);
        } else {
          return infosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public Builder setInfos(
          int index, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.set(index, value);
          onChanged();
        } else {
          infosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public Builder setInfos(
          int index, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.set(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public Builder addInfos(com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(value);
          onChanged();
        } else {
          infosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public Builder addInfos(
          int index, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(index, value);
          onChanged();
        } else {
          infosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public Builder addInfos(
          com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public Builder addInfos(
          int index, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<? extends com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo> values) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          super.addAll(values, infos_);
          onChanged();
        } else {
          infosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public Builder clearInfos() {
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          infosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public Builder removeInfos(int index) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.remove(index);
          onChanged();
        } else {
          infosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder getInfosBuilder(
          int index) {
        return getInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder getInfosOrBuilder(
          int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);  } else {
          return infosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public java.util.List<? extends com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder> 
           getInfosOrBuilderList() {
        if (infosBuilder_ != null) {
          return infosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(infos_);
        }
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder addInfosBuilder() {
        return getInfosFieldBuilder().addBuilder(
            com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder addInfosBuilder(
          int index) {
        return getInfosFieldBuilder().addBuilder(
            index, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .StrengthenGuideInfo infos = 1;</code>
       */
      public java.util.List<com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder> 
           getInfosBuilderList() {
        return getInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder> 
          getInfosFieldBuilder() {
        if (infosBuilder_ == null) {
          infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfo.Builder, com.hawk.game.protocol.StrengthenGuide.StrengthenGuideInfoOrBuilder>(
                  infos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          infos_ = null;
        }
        return infosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:StrengthenGuideInfoRes)
    }

    static {
      defaultInstance = new StrengthenGuideInfoRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StrengthenGuideInfoRes)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StrengthenGuideInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StrengthenGuideInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StrengthenGuideInfoRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StrengthenGuideInfoRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025StrengthenGuide.proto\"`\n\023StrengthenGui" +
      "deInfo\022#\n\005sType\030\001 \002(\0162\024.StrengthenGuideT" +
      "ype\022\020\n\010stageVal\030\002 \002(\005\022\022\n\nmyStageVal\030\003 \002(" +
      "\005\"=\n\026StrengthenGuideInfoRes\022#\n\005infos\030\001 \003" +
      "(\0132\024.StrengthenGuideInfo*^\n\023StrengthenGu" +
      "ideType\022\014\n\010Building\020\001\022\010\n\004Army\020\002\022\r\n\tComma" +
      "nder\020\003\022\013\n\007Science\020\004\022\010\n\004Hero\020\005\022\t\n\005Total\020\031" +
      "*\356\001\n\032StrengthenGuideOtherIDType\022\023\n\017HeroP" +
      "urpleCount\020\001\022\023\n\017HeroOrangeCount\020\002\022\022\n\016Her" +
      "oLevelCount\020\003\022\021\n\rHeroStarCount\020\004\022\017\n\013Scie",
      "nceArms\020\005\022\022\n\016ScienceDevelop\020\006\022\016\n\nScience" +
      "Res\020\007\022\022\n\016ScienceDefence\020\010\022\020\n\014TalentPoint" +
      "s\020\t\022\021\n\rTalentClasses\020\n\022\021\n\rTalentAchieve\020" +
      "\013*N\n\024HeroQualityColorType\022\t\n\005White\020\001\022\t\n\005" +
      "Green\020\002\022\010\n\004Blue\020\003\022\n\n\006Purple\020\004\022\n\n\006Orange\020" +
      "\005*<\n\rTechClassType\022\007\n\003Res\020\001\022\013\n\007Develop\020\002" +
      "\022\013\n\007Defence\020\003\022\010\n\004Arms\020\005B\030\n\026com.hawk.game" +
      ".protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_StrengthenGuideInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_StrengthenGuideInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StrengthenGuideInfo_descriptor,
              new java.lang.String[] { "SType", "StageVal", "MyStageVal", });
          internal_static_StrengthenGuideInfoRes_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_StrengthenGuideInfoRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StrengthenGuideInfoRes_descriptor,
              new java.lang.String[] { "Infos", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
