// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YuriStrike.proto

package com.hawk.game.protocol;

public final class YuriStrike {
  private YuriStrike() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code YuriState}
   */
  public enum YuriState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOCK = 1;</code>
     *
     * <pre>
     * 尤里行军未达成解锁条件
     * </pre>
     */
    LOCK(0, 1),
    /**
     * <code>SCANING = 2;</code>
     *
     * <pre>
     * 准备行军. 尤里搜索中
     * </pre>
     */
    SCANING(1, 2),
    /**
     * <code>MARCH = 3;</code>
     *
     * <pre>
     * 行军中
     * </pre>
     */
    MARCH(2, 3),
    /**
     * <code>YURI_HOLD = 4;</code>
     *
     * <pre>
     * 占领玩家地块中
     * </pre>
     */
    YURI_HOLD(3, 4),
    /**
     * <code>PRE_CLEAN = 5;</code>
     *
     * <pre>
     * 城内攻击尤里胜利, 准备开启净化
     * </pre>
     */
    PRE_CLEAN(4, 5),
    /**
     * <code>CLEAN = 6;</code>
     *
     * <pre>
     * 净化中
     * </pre>
     */
    CLEAN(5, 6),
    /**
     * <code>CLEAN_OVER = 7;</code>
     *
     * <pre>
     * 净化完成了,等收取兵, 准备下一条线
     * </pre>
     */
    CLEAN_OVER(6, 7),
    ;

    /**
     * <code>LOCK = 1;</code>
     *
     * <pre>
     * 尤里行军未达成解锁条件
     * </pre>
     */
    public static final int LOCK_VALUE = 1;
    /**
     * <code>SCANING = 2;</code>
     *
     * <pre>
     * 准备行军. 尤里搜索中
     * </pre>
     */
    public static final int SCANING_VALUE = 2;
    /**
     * <code>MARCH = 3;</code>
     *
     * <pre>
     * 行军中
     * </pre>
     */
    public static final int MARCH_VALUE = 3;
    /**
     * <code>YURI_HOLD = 4;</code>
     *
     * <pre>
     * 占领玩家地块中
     * </pre>
     */
    public static final int YURI_HOLD_VALUE = 4;
    /**
     * <code>PRE_CLEAN = 5;</code>
     *
     * <pre>
     * 城内攻击尤里胜利, 准备开启净化
     * </pre>
     */
    public static final int PRE_CLEAN_VALUE = 5;
    /**
     * <code>CLEAN = 6;</code>
     *
     * <pre>
     * 净化中
     * </pre>
     */
    public static final int CLEAN_VALUE = 6;
    /**
     * <code>CLEAN_OVER = 7;</code>
     *
     * <pre>
     * 净化完成了,等收取兵, 准备下一条线
     * </pre>
     */
    public static final int CLEAN_OVER_VALUE = 7;


    public final int getNumber() { return value; }

    public static YuriState valueOf(int value) {
      switch (value) {
        case 1: return LOCK;
        case 2: return SCANING;
        case 3: return MARCH;
        case 4: return YURI_HOLD;
        case 5: return PRE_CLEAN;
        case 6: return CLEAN;
        case 7: return CLEAN_OVER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<YuriState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<YuriState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<YuriState>() {
            public YuriState findValueByNumber(int number) {
              return YuriState.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hawk.game.protocol.YuriStrike.getDescriptor().getEnumTypes().get(0);
    }

    private static final YuriState[] VALUES = values();

    public static YuriState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private YuriState(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:YuriState)
  }

  public interface YuriStrikeInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .YuriState state = 1;
    /**
     * <code>optional .YuriState state = 1;</code>
     *
     * <pre>
     * 尤里状态
     * </pre>
     */
    boolean hasState();
    /**
     * <code>optional .YuriState state = 1;</code>
     *
     * <pre>
     * 尤里状态
     * </pre>
     */
    com.hawk.game.protocol.YuriStrike.YuriState getState();

    // optional int64 scanStar = 2;
    /**
     * <code>optional int64 scanStar = 2;</code>
     *
     * <pre>
     * 尤里搜索开始 SCANING
     * </pre>
     */
    boolean hasScanStar();
    /**
     * <code>optional int64 scanStar = 2;</code>
     *
     * <pre>
     * 尤里搜索开始 SCANING
     * </pre>
     */
    long getScanStar();

    // optional int64 scanEnd = 3;
    /**
     * <code>optional int64 scanEnd = 3;</code>
     *
     * <pre>
     * 尤里搜索end
     * </pre>
     */
    boolean hasScanEnd();
    /**
     * <code>optional int64 scanEnd = 3;</code>
     *
     * <pre>
     * 尤里搜索end
     * </pre>
     */
    long getScanEnd();

    // optional int64 cleanStart = 4;
    /**
     * <code>optional int64 cleanStart = 4;</code>
     *
     * <pre>
     * 净化开始 CLEAN
     * </pre>
     */
    boolean hasCleanStart();
    /**
     * <code>optional int64 cleanStart = 4;</code>
     *
     * <pre>
     * 净化开始 CLEAN
     * </pre>
     */
    long getCleanStart();

    // optional int64 cleanEnd = 5;
    /**
     * <code>optional int64 cleanEnd = 5;</code>
     *
     * <pre>
     * ....
     * </pre>
     */
    boolean hasCleanEnd();
    /**
     * <code>optional int64 cleanEnd = 5;</code>
     *
     * <pre>
     * ....
     * </pre>
     */
    long getCleanEnd();

    // optional int32 lockArea = 6;
    /**
     * <code>optional int32 lockArea = 6;</code>
     *
     * <pre>
     * 锁定地块的id  对应 YURI_HOLD
     * </pre>
     */
    boolean hasLockArea();
    /**
     * <code>optional int32 lockArea = 6;</code>
     *
     * <pre>
     * 锁定地块的id  对应 YURI_HOLD
     * </pre>
     */
    int getLockArea();

    // optional int32 yuriCfgId = 7;
    /**
     * <code>optional int32 yuriCfgId = 7;</code>
     *
     * <pre>
     * 配置文件id
     * </pre>
     */
    boolean hasYuriCfgId();
    /**
     * <code>optional int32 yuriCfgId = 7;</code>
     *
     * <pre>
     * 配置文件id
     * </pre>
     */
    int getYuriCfgId();

    // optional string yuriMarchId = 8;
    /**
     * <code>optional string yuriMarchId = 8;</code>
     *
     * <pre>
     * MARCH 状态下, 尤里行军id
     * </pre>
     */
    boolean hasYuriMarchId();
    /**
     * <code>optional string yuriMarchId = 8;</code>
     *
     * <pre>
     * MARCH 状态下, 尤里行军id
     * </pre>
     */
    java.lang.String getYuriMarchId();
    /**
     * <code>optional string yuriMarchId = 8;</code>
     *
     * <pre>
     * MARCH 状态下, 尤里行军id
     * </pre>
     */
    com.google.protobuf.ByteString
        getYuriMarchIdBytes();

    // optional int64 yuriMarchStart = 9;
    /**
     * <code>optional int64 yuriMarchStart = 9;</code>
     *
     * <pre>
     * 城外行军开始
     * </pre>
     */
    boolean hasYuriMarchStart();
    /**
     * <code>optional int64 yuriMarchStart = 9;</code>
     *
     * <pre>
     * 城外行军开始
     * </pre>
     */
    long getYuriMarchStart();

    // optional int64 yuriMarchEnd = 10;
    /**
     * <code>optional int64 yuriMarchEnd = 10;</code>
     *
     * <pre>
     * 城外行军到达
     * </pre>
     */
    boolean hasYuriMarchEnd();
    /**
     * <code>optional int64 yuriMarchEnd = 10;</code>
     *
     * <pre>
     * 城外行军到达
     * </pre>
     */
    long getYuriMarchEnd();

    // optional int32 hasReward = 11;
    /**
     * <code>optional int32 hasReward = 11;</code>
     *
     * <pre>
     * 是不事有奖励
     * </pre>
     */
    boolean hasHasReward();
    /**
     * <code>optional int32 hasReward = 11;</code>
     *
     * <pre>
     * 是不事有奖励
     * </pre>
     */
    int getHasReward();
  }
  /**
   * Protobuf type {@code YuriStrikeInfo}
   *
   * <pre>
   **尤里行军详情 根据状态不同变量不一定有值
   * </pre>
   */
  public static final class YuriStrikeInfo extends
      com.google.protobuf.GeneratedMessage
      implements YuriStrikeInfoOrBuilder {
    // Use YuriStrikeInfo.newBuilder() to construct.
    private YuriStrikeInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private YuriStrikeInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final YuriStrikeInfo defaultInstance;
    public static YuriStrikeInfo getDefaultInstance() {
      return defaultInstance;
    }

    public YuriStrikeInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private YuriStrikeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hawk.game.protocol.YuriStrike.YuriState value = com.hawk.game.protocol.YuriStrike.YuriState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                state_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              scanStar_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              scanEnd_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              cleanStart_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              cleanEnd_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              lockArea_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              yuriCfgId_ = input.readInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              yuriMarchId_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              yuriMarchStart_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              yuriMarchEnd_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              hasReward_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.YuriStrike.internal_static_YuriStrikeInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.YuriStrike.internal_static_YuriStrikeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.YuriStrike.YuriStrikeInfo.class, com.hawk.game.protocol.YuriStrike.YuriStrikeInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<YuriStrikeInfo> PARSER =
        new com.google.protobuf.AbstractParser<YuriStrikeInfo>() {
      public YuriStrikeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new YuriStrikeInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<YuriStrikeInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .YuriState state = 1;
    public static final int STATE_FIELD_NUMBER = 1;
    private com.hawk.game.protocol.YuriStrike.YuriState state_;
    /**
     * <code>optional .YuriState state = 1;</code>
     *
     * <pre>
     * 尤里状态
     * </pre>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .YuriState state = 1;</code>
     *
     * <pre>
     * 尤里状态
     * </pre>
     */
    public com.hawk.game.protocol.YuriStrike.YuriState getState() {
      return state_;
    }

    // optional int64 scanStar = 2;
    public static final int SCANSTAR_FIELD_NUMBER = 2;
    private long scanStar_;
    /**
     * <code>optional int64 scanStar = 2;</code>
     *
     * <pre>
     * 尤里搜索开始 SCANING
     * </pre>
     */
    public boolean hasScanStar() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 scanStar = 2;</code>
     *
     * <pre>
     * 尤里搜索开始 SCANING
     * </pre>
     */
    public long getScanStar() {
      return scanStar_;
    }

    // optional int64 scanEnd = 3;
    public static final int SCANEND_FIELD_NUMBER = 3;
    private long scanEnd_;
    /**
     * <code>optional int64 scanEnd = 3;</code>
     *
     * <pre>
     * 尤里搜索end
     * </pre>
     */
    public boolean hasScanEnd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 scanEnd = 3;</code>
     *
     * <pre>
     * 尤里搜索end
     * </pre>
     */
    public long getScanEnd() {
      return scanEnd_;
    }

    // optional int64 cleanStart = 4;
    public static final int CLEANSTART_FIELD_NUMBER = 4;
    private long cleanStart_;
    /**
     * <code>optional int64 cleanStart = 4;</code>
     *
     * <pre>
     * 净化开始 CLEAN
     * </pre>
     */
    public boolean hasCleanStart() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 cleanStart = 4;</code>
     *
     * <pre>
     * 净化开始 CLEAN
     * </pre>
     */
    public long getCleanStart() {
      return cleanStart_;
    }

    // optional int64 cleanEnd = 5;
    public static final int CLEANEND_FIELD_NUMBER = 5;
    private long cleanEnd_;
    /**
     * <code>optional int64 cleanEnd = 5;</code>
     *
     * <pre>
     * ....
     * </pre>
     */
    public boolean hasCleanEnd() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 cleanEnd = 5;</code>
     *
     * <pre>
     * ....
     * </pre>
     */
    public long getCleanEnd() {
      return cleanEnd_;
    }

    // optional int32 lockArea = 6;
    public static final int LOCKAREA_FIELD_NUMBER = 6;
    private int lockArea_;
    /**
     * <code>optional int32 lockArea = 6;</code>
     *
     * <pre>
     * 锁定地块的id  对应 YURI_HOLD
     * </pre>
     */
    public boolean hasLockArea() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 lockArea = 6;</code>
     *
     * <pre>
     * 锁定地块的id  对应 YURI_HOLD
     * </pre>
     */
    public int getLockArea() {
      return lockArea_;
    }

    // optional int32 yuriCfgId = 7;
    public static final int YURICFGID_FIELD_NUMBER = 7;
    private int yuriCfgId_;
    /**
     * <code>optional int32 yuriCfgId = 7;</code>
     *
     * <pre>
     * 配置文件id
     * </pre>
     */
    public boolean hasYuriCfgId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 yuriCfgId = 7;</code>
     *
     * <pre>
     * 配置文件id
     * </pre>
     */
    public int getYuriCfgId() {
      return yuriCfgId_;
    }

    // optional string yuriMarchId = 8;
    public static final int YURIMARCHID_FIELD_NUMBER = 8;
    private java.lang.Object yuriMarchId_;
    /**
     * <code>optional string yuriMarchId = 8;</code>
     *
     * <pre>
     * MARCH 状态下, 尤里行军id
     * </pre>
     */
    public boolean hasYuriMarchId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string yuriMarchId = 8;</code>
     *
     * <pre>
     * MARCH 状态下, 尤里行军id
     * </pre>
     */
    public java.lang.String getYuriMarchId() {
      java.lang.Object ref = yuriMarchId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          yuriMarchId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string yuriMarchId = 8;</code>
     *
     * <pre>
     * MARCH 状态下, 尤里行军id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getYuriMarchIdBytes() {
      java.lang.Object ref = yuriMarchId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        yuriMarchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 yuriMarchStart = 9;
    public static final int YURIMARCHSTART_FIELD_NUMBER = 9;
    private long yuriMarchStart_;
    /**
     * <code>optional int64 yuriMarchStart = 9;</code>
     *
     * <pre>
     * 城外行军开始
     * </pre>
     */
    public boolean hasYuriMarchStart() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 yuriMarchStart = 9;</code>
     *
     * <pre>
     * 城外行军开始
     * </pre>
     */
    public long getYuriMarchStart() {
      return yuriMarchStart_;
    }

    // optional int64 yuriMarchEnd = 10;
    public static final int YURIMARCHEND_FIELD_NUMBER = 10;
    private long yuriMarchEnd_;
    /**
     * <code>optional int64 yuriMarchEnd = 10;</code>
     *
     * <pre>
     * 城外行军到达
     * </pre>
     */
    public boolean hasYuriMarchEnd() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 yuriMarchEnd = 10;</code>
     *
     * <pre>
     * 城外行军到达
     * </pre>
     */
    public long getYuriMarchEnd() {
      return yuriMarchEnd_;
    }

    // optional int32 hasReward = 11;
    public static final int HASREWARD_FIELD_NUMBER = 11;
    private int hasReward_;
    /**
     * <code>optional int32 hasReward = 11;</code>
     *
     * <pre>
     * 是不事有奖励
     * </pre>
     */
    public boolean hasHasReward() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 hasReward = 11;</code>
     *
     * <pre>
     * 是不事有奖励
     * </pre>
     */
    public int getHasReward() {
      return hasReward_;
    }

    private void initFields() {
      state_ = com.hawk.game.protocol.YuriStrike.YuriState.LOCK;
      scanStar_ = 0L;
      scanEnd_ = 0L;
      cleanStart_ = 0L;
      cleanEnd_ = 0L;
      lockArea_ = 0;
      yuriCfgId_ = 0;
      yuriMarchId_ = "";
      yuriMarchStart_ = 0L;
      yuriMarchEnd_ = 0L;
      hasReward_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, state_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, scanStar_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, scanEnd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, cleanStart_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, cleanEnd_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, lockArea_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, yuriCfgId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getYuriMarchIdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, yuriMarchStart_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, yuriMarchEnd_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, hasReward_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, scanStar_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, scanEnd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, cleanStart_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, cleanEnd_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, lockArea_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, yuriCfgId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getYuriMarchIdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, yuriMarchStart_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, yuriMarchEnd_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, hasReward_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.YuriStrike.YuriStrikeInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code YuriStrikeInfo}
     *
     * <pre>
     **尤里行军详情 根据状态不同变量不一定有值
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.YuriStrike.YuriStrikeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.YuriStrike.internal_static_YuriStrikeInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.YuriStrike.internal_static_YuriStrikeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.YuriStrike.YuriStrikeInfo.class, com.hawk.game.protocol.YuriStrike.YuriStrikeInfo.Builder.class);
      }

      // Construct using com.hawk.game.protocol.YuriStrike.YuriStrikeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        state_ = com.hawk.game.protocol.YuriStrike.YuriState.LOCK;
        bitField0_ = (bitField0_ & ~0x00000001);
        scanStar_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        scanEnd_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        cleanStart_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        cleanEnd_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        lockArea_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        yuriCfgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        yuriMarchId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        yuriMarchStart_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        yuriMarchEnd_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        hasReward_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.YuriStrike.internal_static_YuriStrikeInfo_descriptor;
      }

      public com.hawk.game.protocol.YuriStrike.YuriStrikeInfo getDefaultInstanceForType() {
        return com.hawk.game.protocol.YuriStrike.YuriStrikeInfo.getDefaultInstance();
      }

      public com.hawk.game.protocol.YuriStrike.YuriStrikeInfo build() {
        com.hawk.game.protocol.YuriStrike.YuriStrikeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.YuriStrike.YuriStrikeInfo buildPartial() {
        com.hawk.game.protocol.YuriStrike.YuriStrikeInfo result = new com.hawk.game.protocol.YuriStrike.YuriStrikeInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.scanStar_ = scanStar_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.scanEnd_ = scanEnd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cleanStart_ = cleanStart_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cleanEnd_ = cleanEnd_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.lockArea_ = lockArea_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.yuriCfgId_ = yuriCfgId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.yuriMarchId_ = yuriMarchId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.yuriMarchStart_ = yuriMarchStart_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.yuriMarchEnd_ = yuriMarchEnd_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.hasReward_ = hasReward_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.YuriStrike.YuriStrikeInfo) {
          return mergeFrom((com.hawk.game.protocol.YuriStrike.YuriStrikeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.YuriStrike.YuriStrikeInfo other) {
        if (other == com.hawk.game.protocol.YuriStrike.YuriStrikeInfo.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasScanStar()) {
          setScanStar(other.getScanStar());
        }
        if (other.hasScanEnd()) {
          setScanEnd(other.getScanEnd());
        }
        if (other.hasCleanStart()) {
          setCleanStart(other.getCleanStart());
        }
        if (other.hasCleanEnd()) {
          setCleanEnd(other.getCleanEnd());
        }
        if (other.hasLockArea()) {
          setLockArea(other.getLockArea());
        }
        if (other.hasYuriCfgId()) {
          setYuriCfgId(other.getYuriCfgId());
        }
        if (other.hasYuriMarchId()) {
          bitField0_ |= 0x00000080;
          yuriMarchId_ = other.yuriMarchId_;
          onChanged();
        }
        if (other.hasYuriMarchStart()) {
          setYuriMarchStart(other.getYuriMarchStart());
        }
        if (other.hasYuriMarchEnd()) {
          setYuriMarchEnd(other.getYuriMarchEnd());
        }
        if (other.hasHasReward()) {
          setHasReward(other.getHasReward());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.YuriStrike.YuriStrikeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.YuriStrike.YuriStrikeInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .YuriState state = 1;
      private com.hawk.game.protocol.YuriStrike.YuriState state_ = com.hawk.game.protocol.YuriStrike.YuriState.LOCK;
      /**
       * <code>optional .YuriState state = 1;</code>
       *
       * <pre>
       * 尤里状态
       * </pre>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .YuriState state = 1;</code>
       *
       * <pre>
       * 尤里状态
       * </pre>
       */
      public com.hawk.game.protocol.YuriStrike.YuriState getState() {
        return state_;
      }
      /**
       * <code>optional .YuriState state = 1;</code>
       *
       * <pre>
       * 尤里状态
       * </pre>
       */
      public Builder setState(com.hawk.game.protocol.YuriStrike.YuriState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .YuriState state = 1;</code>
       *
       * <pre>
       * 尤里状态
       * </pre>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = com.hawk.game.protocol.YuriStrike.YuriState.LOCK;
        onChanged();
        return this;
      }

      // optional int64 scanStar = 2;
      private long scanStar_ ;
      /**
       * <code>optional int64 scanStar = 2;</code>
       *
       * <pre>
       * 尤里搜索开始 SCANING
       * </pre>
       */
      public boolean hasScanStar() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 scanStar = 2;</code>
       *
       * <pre>
       * 尤里搜索开始 SCANING
       * </pre>
       */
      public long getScanStar() {
        return scanStar_;
      }
      /**
       * <code>optional int64 scanStar = 2;</code>
       *
       * <pre>
       * 尤里搜索开始 SCANING
       * </pre>
       */
      public Builder setScanStar(long value) {
        bitField0_ |= 0x00000002;
        scanStar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 scanStar = 2;</code>
       *
       * <pre>
       * 尤里搜索开始 SCANING
       * </pre>
       */
      public Builder clearScanStar() {
        bitField0_ = (bitField0_ & ~0x00000002);
        scanStar_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 scanEnd = 3;
      private long scanEnd_ ;
      /**
       * <code>optional int64 scanEnd = 3;</code>
       *
       * <pre>
       * 尤里搜索end
       * </pre>
       */
      public boolean hasScanEnd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 scanEnd = 3;</code>
       *
       * <pre>
       * 尤里搜索end
       * </pre>
       */
      public long getScanEnd() {
        return scanEnd_;
      }
      /**
       * <code>optional int64 scanEnd = 3;</code>
       *
       * <pre>
       * 尤里搜索end
       * </pre>
       */
      public Builder setScanEnd(long value) {
        bitField0_ |= 0x00000004;
        scanEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 scanEnd = 3;</code>
       *
       * <pre>
       * 尤里搜索end
       * </pre>
       */
      public Builder clearScanEnd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        scanEnd_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 cleanStart = 4;
      private long cleanStart_ ;
      /**
       * <code>optional int64 cleanStart = 4;</code>
       *
       * <pre>
       * 净化开始 CLEAN
       * </pre>
       */
      public boolean hasCleanStart() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 cleanStart = 4;</code>
       *
       * <pre>
       * 净化开始 CLEAN
       * </pre>
       */
      public long getCleanStart() {
        return cleanStart_;
      }
      /**
       * <code>optional int64 cleanStart = 4;</code>
       *
       * <pre>
       * 净化开始 CLEAN
       * </pre>
       */
      public Builder setCleanStart(long value) {
        bitField0_ |= 0x00000008;
        cleanStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cleanStart = 4;</code>
       *
       * <pre>
       * 净化开始 CLEAN
       * </pre>
       */
      public Builder clearCleanStart() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cleanStart_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 cleanEnd = 5;
      private long cleanEnd_ ;
      /**
       * <code>optional int64 cleanEnd = 5;</code>
       *
       * <pre>
       * ....
       * </pre>
       */
      public boolean hasCleanEnd() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 cleanEnd = 5;</code>
       *
       * <pre>
       * ....
       * </pre>
       */
      public long getCleanEnd() {
        return cleanEnd_;
      }
      /**
       * <code>optional int64 cleanEnd = 5;</code>
       *
       * <pre>
       * ....
       * </pre>
       */
      public Builder setCleanEnd(long value) {
        bitField0_ |= 0x00000010;
        cleanEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cleanEnd = 5;</code>
       *
       * <pre>
       * ....
       * </pre>
       */
      public Builder clearCleanEnd() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cleanEnd_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 lockArea = 6;
      private int lockArea_ ;
      /**
       * <code>optional int32 lockArea = 6;</code>
       *
       * <pre>
       * 锁定地块的id  对应 YURI_HOLD
       * </pre>
       */
      public boolean hasLockArea() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 lockArea = 6;</code>
       *
       * <pre>
       * 锁定地块的id  对应 YURI_HOLD
       * </pre>
       */
      public int getLockArea() {
        return lockArea_;
      }
      /**
       * <code>optional int32 lockArea = 6;</code>
       *
       * <pre>
       * 锁定地块的id  对应 YURI_HOLD
       * </pre>
       */
      public Builder setLockArea(int value) {
        bitField0_ |= 0x00000020;
        lockArea_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lockArea = 6;</code>
       *
       * <pre>
       * 锁定地块的id  对应 YURI_HOLD
       * </pre>
       */
      public Builder clearLockArea() {
        bitField0_ = (bitField0_ & ~0x00000020);
        lockArea_ = 0;
        onChanged();
        return this;
      }

      // optional int32 yuriCfgId = 7;
      private int yuriCfgId_ ;
      /**
       * <code>optional int32 yuriCfgId = 7;</code>
       *
       * <pre>
       * 配置文件id
       * </pre>
       */
      public boolean hasYuriCfgId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 yuriCfgId = 7;</code>
       *
       * <pre>
       * 配置文件id
       * </pre>
       */
      public int getYuriCfgId() {
        return yuriCfgId_;
      }
      /**
       * <code>optional int32 yuriCfgId = 7;</code>
       *
       * <pre>
       * 配置文件id
       * </pre>
       */
      public Builder setYuriCfgId(int value) {
        bitField0_ |= 0x00000040;
        yuriCfgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 yuriCfgId = 7;</code>
       *
       * <pre>
       * 配置文件id
       * </pre>
       */
      public Builder clearYuriCfgId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        yuriCfgId_ = 0;
        onChanged();
        return this;
      }

      // optional string yuriMarchId = 8;
      private java.lang.Object yuriMarchId_ = "";
      /**
       * <code>optional string yuriMarchId = 8;</code>
       *
       * <pre>
       * MARCH 状态下, 尤里行军id
       * </pre>
       */
      public boolean hasYuriMarchId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string yuriMarchId = 8;</code>
       *
       * <pre>
       * MARCH 状态下, 尤里行军id
       * </pre>
       */
      public java.lang.String getYuriMarchId() {
        java.lang.Object ref = yuriMarchId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          yuriMarchId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string yuriMarchId = 8;</code>
       *
       * <pre>
       * MARCH 状态下, 尤里行军id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getYuriMarchIdBytes() {
        java.lang.Object ref = yuriMarchId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          yuriMarchId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string yuriMarchId = 8;</code>
       *
       * <pre>
       * MARCH 状态下, 尤里行军id
       * </pre>
       */
      public Builder setYuriMarchId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        yuriMarchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string yuriMarchId = 8;</code>
       *
       * <pre>
       * MARCH 状态下, 尤里行军id
       * </pre>
       */
      public Builder clearYuriMarchId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        yuriMarchId_ = getDefaultInstance().getYuriMarchId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string yuriMarchId = 8;</code>
       *
       * <pre>
       * MARCH 状态下, 尤里行军id
       * </pre>
       */
      public Builder setYuriMarchIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        yuriMarchId_ = value;
        onChanged();
        return this;
      }

      // optional int64 yuriMarchStart = 9;
      private long yuriMarchStart_ ;
      /**
       * <code>optional int64 yuriMarchStart = 9;</code>
       *
       * <pre>
       * 城外行军开始
       * </pre>
       */
      public boolean hasYuriMarchStart() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 yuriMarchStart = 9;</code>
       *
       * <pre>
       * 城外行军开始
       * </pre>
       */
      public long getYuriMarchStart() {
        return yuriMarchStart_;
      }
      /**
       * <code>optional int64 yuriMarchStart = 9;</code>
       *
       * <pre>
       * 城外行军开始
       * </pre>
       */
      public Builder setYuriMarchStart(long value) {
        bitField0_ |= 0x00000100;
        yuriMarchStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 yuriMarchStart = 9;</code>
       *
       * <pre>
       * 城外行军开始
       * </pre>
       */
      public Builder clearYuriMarchStart() {
        bitField0_ = (bitField0_ & ~0x00000100);
        yuriMarchStart_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 yuriMarchEnd = 10;
      private long yuriMarchEnd_ ;
      /**
       * <code>optional int64 yuriMarchEnd = 10;</code>
       *
       * <pre>
       * 城外行军到达
       * </pre>
       */
      public boolean hasYuriMarchEnd() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 yuriMarchEnd = 10;</code>
       *
       * <pre>
       * 城外行军到达
       * </pre>
       */
      public long getYuriMarchEnd() {
        return yuriMarchEnd_;
      }
      /**
       * <code>optional int64 yuriMarchEnd = 10;</code>
       *
       * <pre>
       * 城外行军到达
       * </pre>
       */
      public Builder setYuriMarchEnd(long value) {
        bitField0_ |= 0x00000200;
        yuriMarchEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 yuriMarchEnd = 10;</code>
       *
       * <pre>
       * 城外行军到达
       * </pre>
       */
      public Builder clearYuriMarchEnd() {
        bitField0_ = (bitField0_ & ~0x00000200);
        yuriMarchEnd_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 hasReward = 11;
      private int hasReward_ ;
      /**
       * <code>optional int32 hasReward = 11;</code>
       *
       * <pre>
       * 是不事有奖励
       * </pre>
       */
      public boolean hasHasReward() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 hasReward = 11;</code>
       *
       * <pre>
       * 是不事有奖励
       * </pre>
       */
      public int getHasReward() {
        return hasReward_;
      }
      /**
       * <code>optional int32 hasReward = 11;</code>
       *
       * <pre>
       * 是不事有奖励
       * </pre>
       */
      public Builder setHasReward(int value) {
        bitField0_ |= 0x00000400;
        hasReward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hasReward = 11;</code>
       *
       * <pre>
       * 是不事有奖励
       * </pre>
       */
      public Builder clearHasReward() {
        bitField0_ = (bitField0_ & ~0x00000400);
        hasReward_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YuriStrikeInfo)
    }

    static {
      defaultInstance = new YuriStrikeInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:YuriStrikeInfo)
  }

  public interface PBAtkYuriRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 win = 1;
    /**
     * <code>optional int32 win = 1;</code>
     *
     * <pre>
     * 1 win 0 lose
     * </pre>
     */
    boolean hasWin();
    /**
     * <code>optional int32 win = 1;</code>
     *
     * <pre>
     * 1 win 0 lose
     * </pre>
     */
    int getWin();
  }
  /**
   * Protobuf type {@code PBAtkYuriResp}
   *
   * <pre>
   * 城内反击结果
   * </pre>
   */
  public static final class PBAtkYuriResp extends
      com.google.protobuf.GeneratedMessage
      implements PBAtkYuriRespOrBuilder {
    // Use PBAtkYuriResp.newBuilder() to construct.
    private PBAtkYuriResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBAtkYuriResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBAtkYuriResp defaultInstance;
    public static PBAtkYuriResp getDefaultInstance() {
      return defaultInstance;
    }

    public PBAtkYuriResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBAtkYuriResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              win_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hawk.game.protocol.YuriStrike.internal_static_PBAtkYuriResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hawk.game.protocol.YuriStrike.internal_static_PBAtkYuriResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hawk.game.protocol.YuriStrike.PBAtkYuriResp.class, com.hawk.game.protocol.YuriStrike.PBAtkYuriResp.Builder.class);
    }

    public static com.google.protobuf.Parser<PBAtkYuriResp> PARSER =
        new com.google.protobuf.AbstractParser<PBAtkYuriResp>() {
      public PBAtkYuriResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBAtkYuriResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBAtkYuriResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 win = 1;
    public static final int WIN_FIELD_NUMBER = 1;
    private int win_;
    /**
     * <code>optional int32 win = 1;</code>
     *
     * <pre>
     * 1 win 0 lose
     * </pre>
     */
    public boolean hasWin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 win = 1;</code>
     *
     * <pre>
     * 1 win 0 lose
     * </pre>
     */
    public int getWin() {
      return win_;
    }

    private void initFields() {
      win_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, win_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, win_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hawk.game.protocol.YuriStrike.PBAtkYuriResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PBAtkYuriResp}
     *
     * <pre>
     * 城内反击结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hawk.game.protocol.YuriStrike.PBAtkYuriRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hawk.game.protocol.YuriStrike.internal_static_PBAtkYuriResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hawk.game.protocol.YuriStrike.internal_static_PBAtkYuriResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hawk.game.protocol.YuriStrike.PBAtkYuriResp.class, com.hawk.game.protocol.YuriStrike.PBAtkYuriResp.Builder.class);
      }

      // Construct using com.hawk.game.protocol.YuriStrike.PBAtkYuriResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        win_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hawk.game.protocol.YuriStrike.internal_static_PBAtkYuriResp_descriptor;
      }

      public com.hawk.game.protocol.YuriStrike.PBAtkYuriResp getDefaultInstanceForType() {
        return com.hawk.game.protocol.YuriStrike.PBAtkYuriResp.getDefaultInstance();
      }

      public com.hawk.game.protocol.YuriStrike.PBAtkYuriResp build() {
        com.hawk.game.protocol.YuriStrike.PBAtkYuriResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hawk.game.protocol.YuriStrike.PBAtkYuriResp buildPartial() {
        com.hawk.game.protocol.YuriStrike.PBAtkYuriResp result = new com.hawk.game.protocol.YuriStrike.PBAtkYuriResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.win_ = win_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hawk.game.protocol.YuriStrike.PBAtkYuriResp) {
          return mergeFrom((com.hawk.game.protocol.YuriStrike.PBAtkYuriResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hawk.game.protocol.YuriStrike.PBAtkYuriResp other) {
        if (other == com.hawk.game.protocol.YuriStrike.PBAtkYuriResp.getDefaultInstance()) return this;
        if (other.hasWin()) {
          setWin(other.getWin());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hawk.game.protocol.YuriStrike.PBAtkYuriResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hawk.game.protocol.YuriStrike.PBAtkYuriResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 win = 1;
      private int win_ ;
      /**
       * <code>optional int32 win = 1;</code>
       *
       * <pre>
       * 1 win 0 lose
       * </pre>
       */
      public boolean hasWin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 win = 1;</code>
       *
       * <pre>
       * 1 win 0 lose
       * </pre>
       */
      public int getWin() {
        return win_;
      }
      /**
       * <code>optional int32 win = 1;</code>
       *
       * <pre>
       * 1 win 0 lose
       * </pre>
       */
      public Builder setWin(int value) {
        bitField0_ |= 0x00000001;
        win_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 win = 1;</code>
       *
       * <pre>
       * 1 win 0 lose
       * </pre>
       */
      public Builder clearWin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        win_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PBAtkYuriResp)
    }

    static {
      defaultInstance = new PBAtkYuriResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PBAtkYuriResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_YuriStrikeInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_YuriStrikeInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBAtkYuriResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBAtkYuriResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020YuriStrike.proto\"\357\001\n\016YuriStrikeInfo\022\031\n" +
      "\005state\030\001 \001(\0162\n.YuriState\022\020\n\010scanStar\030\002 \001" +
      "(\003\022\017\n\007scanEnd\030\003 \001(\003\022\022\n\ncleanStart\030\004 \001(\003\022" +
      "\020\n\010cleanEnd\030\005 \001(\003\022\020\n\010lockArea\030\006 \001(\005\022\021\n\ty" +
      "uriCfgId\030\007 \001(\005\022\023\n\013yuriMarchId\030\010 \001(\t\022\026\n\016y" +
      "uriMarchStart\030\t \001(\003\022\024\n\014yuriMarchEnd\030\n \001(" +
      "\003\022\021\n\thasReward\030\013 \001(\005\"\034\n\rPBAtkYuriResp\022\013\n" +
      "\003win\030\001 \001(\005*f\n\tYuriState\022\010\n\004LOCK\020\001\022\013\n\007SCA" +
      "NING\020\002\022\t\n\005MARCH\020\003\022\r\n\tYURI_HOLD\020\004\022\r\n\tPRE_" +
      "CLEAN\020\005\022\t\n\005CLEAN\020\006\022\016\n\nCLEAN_OVER\020\007B\030\n\026co",
      "m.hawk.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_YuriStrikeInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_YuriStrikeInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_YuriStrikeInfo_descriptor,
              new java.lang.String[] { "State", "ScanStar", "ScanEnd", "CleanStart", "CleanEnd", "LockArea", "YuriCfgId", "YuriMarchId", "YuriMarchStart", "YuriMarchEnd", "HasReward", });
          internal_static_PBAtkYuriResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PBAtkYuriResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBAtkYuriResp_descriptor,
              new java.lang.String[] { "Win", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
